import type { SpellRow } from './types';

export const C0: readonly SpellRow[] = [
  [
    'Respingo Ácido',
    'con',
    '1 ação',
    '18 metros',
    'V, S',
    'Instantânea',
    'fe ma',
    'Uma bolha de ácido atinge uma ou duas criaturas adjacentes entre si; cada uma faz salvaguarda de Destreza ou sofre 1d6 de dano ácido.',
    'Dano 2d6, 3d6 e 4d6 nos níveis 5, 11 e 17.',
  ],
  [
    'Proteção Contra Lâminas',
    'abj',
    '1 ação',
    'Pessoal',
    'V, S',
    '1 rodada',
    'ba bx fe ma',
    'Até o fim do seu próximo turno, você tem resistência a dano cortante, perfurante e contundente de ataques com armas.',
  ],
  [
    'Toque Arrepiante',
    'nec',
    '1 ação',
    '36 metros',
    'V, S',
    '1 rodada',
    'bx fe ma',
    'Uma mão espectral causa 1d8 de dano necrótico (ataque de magia à distância) e impede a criatura de recuperar PV até o início do seu próximo turno. Mortos-vivos têm desvantagem nos ataques contra você.',
    'Dano 2d8, 3d8 e 4d8 nos níveis 5, 11 e 17.',
  ],
  [
    'Luzes Dançantes',
    'evo',
    '1 ação',
    '36 metros',
    'V, S, M (um pouco de fósforo ou de folha de ágave)',
    'Concentração, até 1 minuto',
    'ba fe ma',
    'Cria até quatro luzes do tamanho de tochas, ou uma forma vagamente humanoide, que você move com uma ação bônus até 18 metros por turno.',
  ],
  [
    'Arte Druídica',
    'tra',
    '1 ação',
    '9 metros',
    'V, S',
    'Instantânea',
    'dr',
    'Efeitos naturais pequenos: prever o tempo, fazer uma flor desabrochar, criar um sensor inofensivo ou acender/apagar uma chama pequena.',
  ],
  [
    'Rajada Mística',
    'evo',
    '1 ação',
    '36 metros',
    'V, S',
    'Instantânea',
    'bx',
    'Um raio de energia causa 1d10 de dano de força (ataque de magia à distância).',
    'Raios adicionais nos níveis 5, 11 e 17: 2, 3 e 4 raios, cada um com seu ataque.',
  ],
  [
    'Raio de Fogo',
    'evo',
    '1 ação',
    '36 metros',
    'V, S',
    'Instantânea',
    'fe ma',
    'Lança uma chama que causa 1d10 de dano de fogo (ataque de magia à distância) e acende objetos inflamáveis não vestidos.',
    'Dano 2d10, 3d10 e 4d10 nos níveis 5, 11 e 17.',
  ],
  [
    'Amigos',
    'enc',
    '1 ação',
    'Pessoal',
    'S, M (um pouco de maquiagem)',
    'Concentração, até 1 minuto',
    'ba bx fe ma',
    'Você tem vantagem em testes de Carisma contra uma criatura não hostil. Ao fim, ela percebe que foi encantada e pode ficar hostil.',
  ],
  [
    'Orientação',
    'adi',
    '1 ação',
    'Toque',
    'V, S',
    'Concentração, até 1 minuto',
    'cl dr',
    'A criatura tocada pode rolar 1d4 e somar ao resultado de um teste de atributo, uma vez, antes do fim da magia.',
  ],
  [
    'Luz',
    'evo',
    '1 ação',
    'Toque',
    'V, M (um vaga-lume ou musgo fosforescente)',
    '1 hora',
    'ba cl fe ma',
    'Um objeto tocado emite luz plena em 6 metros e penumbra por mais 6 metros. Uma criatura hostil que segura o objeto faz salvaguarda de Destreza para evitar o efeito.',
  ],
  [
    'Mãos Mágicas',
    'con',
    '1 ação',
    '9 metros',
    'V, S',
    '1 minuto',
    'ba bx fe ma',
    'Uma mão espectral manipula objetos, abre portas e carrega até 5 kg. Pode ser movida 9 metros por ação; não ataca nem ativa itens mágicos.',
  ],
  [
    'Reparar',
    'tra',
    '1 minuto',
    'Toque',
    'V, S, M (duas magnetitas)',
    'Instantânea',
    'ba cl dr fe ma',
    'Conserta uma quebra ou rasgo em um objeto tocado, desde que o defeito não passe de 30 cm.',
  ],
  [
    'Mensagem',
    'tra',
    '1 ação',
    '36 metros',
    'V, S, M (um pedaço de fio de cobre)',
    '1 rodada',
    'ba fe ma',
    'Você sussurra uma mensagem a uma criatura no alcance, que a ouve e pode responder em sussurro. Atravessa obstáculos, mas não barreiras totalmente fechadas.',
  ],
  [
    'Ilusão Menor',
    'ilu',
    '1 ação',
    '9 metros',
    'S, M (um pouco de lã)',
    '1 minuto',
    'ba bx fe ma',
    'Cria um som ou uma imagem de um objeto em um cubo de 1,5 metro. Quem examina a ilusão e passa em Inteligência (Investigação) percebe que é falsa.',
  ],
  [
    'Borrifo Venenoso',
    'con',
    '1 ação',
    '3 metros',
    'V, S',
    'Instantânea',
    'bx dr fe ma',
    'Uma nuvem de gás tóxico: a criatura faz salvaguarda de Constituição ou sofre 1d12 de dano de veneno.',
    'Dano 2d12, 3d12 e 4d12 nos níveis 5, 11 e 17.',
  ],
  [
    'Prestidigitação',
    'tra',
    '1 ação',
    '3 metros',
    'V, S',
    'Até 1 hora',
    'ba bx fe ma',
    'Pequenos truques mágicos: limpar ou sujar, acender uma vela, aquecer, resfriar, temperar, criar uma marca ou um bibelô.',
  ],
  [
    'Criar Chamas',
    'con',
    '1 ação',
    'Pessoal',
    'V, S',
    '10 minutos',
    'dr',
    'Uma chama na sua mão ilumina como tocha. Você pode lançá-la (36 metros) como ataque de magia à distância para causar 1d8 de dano de fogo.',
    'Dano 2d8, 3d8 e 4d8 nos níveis 5, 11 e 17.',
  ],
  [
    'Raio de Gelo',
    'evo',
    '1 ação',
    '18 metros',
    'V, S',
    'Instantânea',
    'fe ma',
    'Um raio frio causa 1d8 de dano de gelo (ataque de magia à distância) e reduz o deslocamento do alvo em 3 metros até o início do seu próximo turno.',
    'Dano 2d8, 3d8 e 4d8 nos níveis 5, 11 e 17.',
  ],
  [
    'Resistência',
    'abj',
    '1 ação',
    'Toque',
    'V, S, M (uma capa em miniatura)',
    'Concentração, até 1 minuto',
    'cl dr',
    'A criatura tocada pode rolar 1d4 e somar a uma salvaguarda, uma vez, antes do fim da magia.',
  ],
  [
    'Chama Sagrada',
    'evo',
    '1 ação',
    '18 metros',
    'V, S',
    'Instantânea',
    'cl',
    'Uma luz desce sobre a criatura, que faz salvaguarda de Destreza (sem benefício de cobertura) ou sofre 1d8 de dano radiante.',
    'Dano 2d8, 3d8 e 4d8 nos níveis 5, 11 e 17.',
  ],
  [
    'Cajado Místico',
    'tra',
    '1 ação bônus',
    'Toque',
    'V, S, M (visco, folha de trevo e um cajado ou clava)',
    '1 minuto',
    'dr',
    'A arma de madeira usa seu atributo de conjuração em vez de Força nos ataques e dano, e o dado de dano vira d8.',
  ],
  [
    'Toque Chocante',
    'evo',
    '1 ação',
    'Toque',
    'V, S',
    'Instantânea',
    'fe ma',
    'Descarga elétrica: 1d8 de dano elétrico (ataque de magia corpo a corpo, com vantagem contra alvos de armadura de metal). O alvo não pode usar reações até o próximo turno dele.',
    'Dano 2d8, 3d8 e 4d8 nos níveis 5, 11 e 17.',
  ],
  [
    'Poupar os Moribundos',
    'nec',
    '1 ação',
    'Toque',
    'V, S',
    'Instantânea',
    'cl',
    'Uma criatura viva com 0 PV é estabilizada.',
  ],
  [
    'Taumaturgia',
    'tra',
    '1 ação',
    '9 metros',
    'V',
    'Até 1 minuto',
    'cl',
    'Manifestações sobrenaturais menores: voz trovejante, tremor, chamas que tremulam, portas que se abrem, olhos que mudam.',
  ],
  [
    'Chicote de Espinhos',
    'tra',
    '1 ação',
    '9 metros',
    'V, S, M (o caule de uma planta com espinhos)',
    'Instantânea',
    'dr',
    'Um chicote de vinhas causa 1d6 de dano perfurante (ataque de magia corpo a corpo) e, se o alvo for Grande ou menor, o puxa até 3 metros para perto de você.',
    'Dano 2d6, 3d6 e 4d6 nos níveis 5, 11 e 17.',
  ],
  [
    'Golpe Certeiro',
    'adi',
    '1 ação',
    '9 metros',
    'S',
    'Concentração, até 1 rodada',
    'ba bx fe ma',
    'Você tem vantagem na sua primeira jogada de ataque contra o alvo no seu próximo turno.',
  ],
  [
    'Zombaria Dolorosa',
    'enc',
    '1 ação',
    '18 metros',
    'V',
    'Instantânea',
    'ba',
    'Insultos mágicos: o alvo faz salvaguarda de Sabedoria ou sofre 1d4 de dano psíquico e tem desvantagem no próximo ataque que fizer.',
    'Dano 2d4, 3d4 e 4d4 nos níveis 5, 11 e 17.',
  ],
];
