import type { SpellRow } from './types';

export const C1: readonly SpellRow[] = [
  [
    'Alarme',
    'abj',
    '1 minuto (ritual)',
    '9 metros',
    'V, S, M (um sino e fio de prata)',
    '8 horas',
    'pt ma',
    'Define um alarme contra intrusos em uma porta, janela ou área de até um cubo de 6 metros. Você escolhe se soa mentalmente ou como um som audível.',
  ],
  [
    'Amizade Animal',
    'enc',
    '1 ação',
    '9 metros',
    'V, S, M (um pouco de comida)',
    '24 horas',
    'ba dr pt',
    'Uma fera com Inteligência 3 ou menos faz salvaguarda de Sabedoria ou fica enfeitiçada por você, que a convence de que não é uma ameaça.',
    'Uma fera adicional por círculo acima do 1º.',
  ],
  [
    'Perdição',
    'enc',
    '1 ação',
    '9 metros',
    'V, S, M (uma gota de sangue)',
    'Concentração, até 1 minuto',
    'ba cl',
    'Até três criaturas fazem salvaguarda de Carisma; as que falharem subtraem 1d4 de ataques e salvaguardas.',
    'Uma criatura adicional por círculo acima do 1º.',
  ],
  [
    'Bênção',
    'enc',
    '1 ação',
    '9 metros',
    'V, S, M (um borrifo de água benta)',
    'Concentração, até 1 minuto',
    'cl pa',
    'Até três criaturas somam 1d4 às jogadas de ataque e salvaguardas.',
    'Uma criatura adicional por círculo acima do 1º.',
  ],
  [
    'Mãos Flamejantes',
    'evo',
    '1 ação',
    'Pessoal (cone de 4,5 metros)',
    'V, S',
    'Instantânea',
    'fe ma',
    'Chamas saem de suas mãos: salvaguarda de Destreza, 3d6 de dano de fogo na falha ou metade na bem-sucedida. Acende objetos inflamáveis.',
    '+1d6 por círculo acima do 1º.',
  ],
  [
    'Enfeitiçar Pessoa',
    'enc',
    '1 ação',
    '9 metros',
    'V, S',
    '1 hora',
    'ba bx dr fe ma',
    'Um humanoide faz salvaguarda de Sabedoria (com vantagem se você ou aliados o estiverem combatendo) ou fica enfeitiçado, tratando você como amigo. Ao fim, ele sabe que foi enfeitiçado.',
    'Uma criatura adicional por círculo acima do 1º.',
  ],
  [
    'Cascata de Cores',
    'ilu',
    '1 ação',
    'Pessoal (cone de 4,5 metros)',
    'V, S, M (pó ou areia colorida)',
    '1 rodada',
    'fe ma',
    'Luzes cegam criaturas, começando pelas de menos PV, em um total de 6d10 PV. Elas ficam cegas até o fim do seu próximo turno.',
    '+2d10 PV por círculo acima do 1º.',
  ],
  [
    'Comando',
    'enc',
    '1 ação',
    '18 metros',
    'V',
    '1 rodada',
    'cl pa',
    'Você dá uma ordem de uma palavra; a criatura faz salvaguarda de Sabedoria ou a obedece no próximo turno (aproximar-se, largar, fugir, cair, parar).',
    'Uma criatura adicional por círculo acima do 1º.',
  ],
  [
    'Compreender Idiomas',
    'adi',
    '1 ação (ritual)',
    'Pessoal',
    'V, S, M (pitada de fuligem e sal)',
    '1 hora',
    'ba bx fe ma',
    'Você entende a linguagem falada que ouve e o texto escrito que toca. Não revela significados ocultos nem lê códigos.',
  ],
  [
    'Criar ou Destruir Água',
    'tra',
    '1 ação',
    '9 metros',
    'V, S, M (gotas de água ou pó de areia)',
    'Instantânea',
    'cl dr',
    'Cria até 40 litros de água limpa, ou destrói a mesma quantidade (inclusive névoa em um cubo de 9 metros).',
    'Quantidade e área crescem 10 litros / 1,5 metro por círculo acima do 1º.',
  ],
  [
    'Curar Ferimentos',
    'evo',
    '1 ação',
    'Toque',
    'V, S',
    'Instantânea',
    'ba cl dr pa pt',
    'Uma criatura tocada recupera 1d8 + seu modificador de atributo de conjuração em PV. Não afeta mortos-vivos nem constructos.',
    '+1d8 por círculo acima do 1º.',
  ],
  [
    'Detectar o Bem e o Mal',
    'adi',
    '1 ação',
    'Pessoal',
    'V, S',
    'Concentração, até 10 minutos',
    'cl pa',
    'Você sente aberrações, celestiais, corruptores, elementais, fadas e mortos-vivos a até 9 metros, além de lugares ou objetos consagrados ou profanados.',
  ],
  [
    'Detectar Magia',
    'adi',
    '1 ação (ritual)',
    'Pessoal',
    'V, S',
    'Concentração, até 10 minutos',
    'ba cl dr pa pt fe ma',
    'Você sente a presença de magia a até 9 metros e, com uma ação, vê uma aura ao redor de criaturas ou objetos mágicos, descobrindo sua escola.',
  ],
  [
    'Detectar Venenos e Doenças',
    'adi',
    '1 ação (ritual)',
    'Pessoal',
    'V, S, M (uma folha de teixo)',
    'Concentração, até 10 minutos',
    'cl dr pa pt',
    'Você sente venenos, criaturas venenosas e doenças a até 9 metros, e identifica o tipo de cada um.',
  ],
  [
    'Disfarçar-se',
    'ilu',
    '1 ação',
    'Pessoal',
    'V, S',
    '1 hora',
    'ba bx fe ma',
    'Muda sua aparência, roupas e equipamento (mantendo o tamanho aproximado e a forma humanoide). Um exame físico revela a ilusão.',
  ],
  [
    'Favor Divino',
    'evo',
    '1 ação bônus',
    'Pessoal',
    'V, S',
    'Concentração, até 1 minuto',
    'pa',
    'Suas armas causam 1d4 de dano radiante extra em cada acerto.',
  ],
  [
    'Constrição',
    'con',
    '1 ação',
    '27 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'dr',
    'Vinhas e plantas prendem em uma área de 6 metros quadrados; criaturas fazem salvaguarda de Força ou ficam impedidas. O terreno vira difícil.',
  ],
  [
    'Retirada Acelerada',
    'tra',
    '1 ação bônus',
    'Pessoal',
    'V, S',
    'Concentração, até 10 minutos',
    'bx fe ma',
    'Você usa Correr como ação bônus ao conjurar e, em cada turno, enquanto durar.',
  ],
  [
    'Fogo Feérico',
    'evo',
    '1 ação',
    '18 metros',
    'V',
    'Concentração, até 1 minuto',
    'ba dr',
    'Criaturas e objetos em um cubo de 6 metros fazem salvaguarda de Destreza ou ficam delineados por luz colorida: ataques contra elas têm vantagem e elas não podem ficar invisíveis.',
  ],
  [
    'Vida Falsa',
    'nec',
    '1 ação',
    'Pessoal',
    'V, S, M (um pouco de álcool ou destilado)',
    '1 hora',
    'fe ma',
    'Você ganha 1d4 + 4 PV temporários.',
    '+5 PV temporários por círculo acima do 1º.',
  ],
  [
    'Queda Suave',
    'tra',
    '1 reação',
    '18 metros',
    'V, M (uma pequena pena)',
    '1 minuto',
    'ba fe ma',
    'Até cinco criaturas em queda têm a velocidade de queda reduzida a 18 metros por rodada e não sofrem dano de queda.',
  ],
  [
    'Convocar Familiar',
    'con',
    '1 hora (ritual)',
    '3 metros',
    'V, S, M (carvão, incenso e ervas no valor de 10 po, queimados em braseiro)',
    'Instantânea',
    'ma',
    'Você ganha um espírito familiar em forma de animal pequeno que age de forma independente, entrega magias de toque e compartilha seus sentidos. Se reduzido a 0 PV, desaparece.',
  ],
  [
    'Névoa',
    'con',
    '1 ação',
    '36 metros',
    'V, S',
    'Concentração, até 1 hora',
    'dr pt fe ma',
    'Cria uma esfera de névoa de 6 metros de raio que obscurece totalmente a visão. Um vento forte a dispersa.',
    'Raio +6 metros por círculo acima do 1º.',
  ],
  [
    'Bagas Boas',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (um raminho de visco)',
    'Instantânea',
    'dr pt',
    'Cria até dez bagas; cada uma cura 1 PV e nutre por um dia, e perde a magia após 24 horas.',
  ],
  [
    'Graxa',
    'con',
    '1 ação',
    '18 metros',
    'V, S, M (um pouco de gordura de porco ou manteiga)',
    '1 minuto',
    'ma',
    'Cobre um quadrado de 3 metros de lado com graxa, tornando-o terreno difícil. Criaturas fazem salvaguarda de Destreza ou caem de bruços.',
  ],
  [
    'Raio Guia',
    'evo',
    '1 ação',
    '36 metros',
    'V, S',
    '1 rodada',
    'cl',
    'Ataque de magia à distância causa 4d6 de dano radiante; o próximo ataque contra o alvo antes do fim do seu turno seguinte tem vantagem.',
    '+1d6 por círculo acima do 1º.',
  ],
  [
    'Palavra de Cura',
    'evo',
    '1 ação bônus',
    '18 metros',
    'V',
    'Instantânea',
    'ba cl dr',
    'Uma criatura que você vê recupera 1d4 + seu modificador de atributo de conjuração em PV.',
    '+1d4 por círculo acima do 1º.',
  ],
  [
    'Repreensão Diabólica',
    'evo',
    '1 reação',
    '18 metros',
    'V, S',
    'Instantânea',
    'bx',
    'Quando você sofre dano de uma criatura que vê, ela faz salvaguarda de Destreza ou sofre 2d10 de dano de fogo (metade se passar).',
    '+1d10 por círculo acima do 1º.',
  ],
  [
    'Heroísmo',
    'enc',
    '1 ação',
    'Toque',
    'V, S',
    'Concentração, até 1 minuto',
    'ba pa',
    'A criatura tocada fica imune a medo e ganha PV temporários iguais ao seu modificador de atributo de conjuração no início de cada turno dela.',
    'Uma criatura adicional por círculo acima do 1º.',
  ],
  [
    'Risada Hilária de Tasha',
    'enc',
    '1 ação',
    '9 metros',
    'V, S, M (tortas pequenas e uma pena)',
    'Concentração, até 1 minuto',
    'ba ma',
    'Uma criatura faz salvaguarda de Sabedoria ou cai no chão rindo, incapacitada e caída. Repete a salvaguarda ao sofrer dano e ao fim de cada turno.',
  ],
  [
    'Marca do Caçador',
    'adi',
    '1 ação bônus',
    '27 metros',
    'V',
    'Concentração, até 1 hora',
    'pt',
    'Você marca uma criatura: causa 1d6 de dano extra com ataques com arma contra ela e tem vantagem em testes para encontrá-la. Pode mover a marca quando ela morre.',
    'Duração maior em círculos mais altos (até 24 horas).',
  ],
  [
    'Identificar',
    'adi',
    '1 minuto (ritual)',
    'Toque',
    'V, S, M (uma pérola de 100 po e uma pena de coruja)',
    'Instantânea',
    'ba ma',
    'Você descobre as propriedades mágicas de um objeto ou criatura tocada, como usar ou ativar, e quais magias o afetam.',
  ],
  [
    'Escrita Ilusória',
    'ilu',
    '1 minuto (ritual)',
    'Toque',
    'S, M (tinta de chumbo, no valor de 10 po)',
    '10 dias',
    'ba bx ma',
    'Você escreve em pergaminho um texto que só um leitor escolhido consegue ler; para os outros, parece outra escrita ou algo sem sentido.',
  ],
  [
    'Infligir Ferimentos',
    'nec',
    '1 ação',
    'Toque',
    'V, S',
    'Instantânea',
    'cl',
    'Ataque de magia corpo a corpo causa 3d10 de dano necrótico.',
    '+1d10 por círculo acima do 1º.',
  ],
  [
    'Salto',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (uma pata de gafanhoto)',
    '1 minuto',
    'dr pt fe ma',
    'A criatura tocada triplica a distância dos seus saltos.',
  ],
  [
    'Passos Largos',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (uma pitada de terra)',
    '1 hora',
    'ba dr pt ma',
    'O deslocamento da criatura tocada aumenta em 3 metros.',
  ],
  [
    'Armadura Arcana',
    'abj',
    '1 ação',
    'Toque',
    'V, S, M (um pedaço de couro curtido)',
    '8 horas',
    'fe ma',
    'Uma criatura sem armadura tocada passa a ter CA 13 + modificador de Destreza.',
  ],
  [
    'Mísseis Mágicos',
    'evo',
    '1 ação',
    '36 metros',
    'V, S',
    'Instantânea',
    'fe ma',
    'Três dardos de força acertam automaticamente, cada um causando 1d4 + 1 de dano de força. Podem ser divididos entre alvos.',
    '+1 dardo por círculo acima do 1º.',
  ],
  [
    'Proteção Contra o Bem e o Mal',
    'abj',
    '1 ação',
    'Toque',
    'V, S, M (água benta ou pó de prata e ferro)',
    'Concentração, até 10 minutos',
    'cl pa bx ma',
    'Protege uma criatura contra aberrações, celestiais, elementais, fadas, corruptores e mortos-vivos: eles têm desvantagem nos ataques contra ela e não podem enfeitiçá-la, amedrontá-la ou possuí-la.',
  ],
  [
    'Purificar Alimentos e Bebidas',
    'tra',
    '1 ação (ritual)',
    '3 metros',
    'V, S',
    'Instantânea',
    'cl dr pa',
    'Remove veneno e doença de comida e bebida não mágicas em uma esfera de 1,5 metro de raio.',
  ],
  [
    'Santuário',
    'abj',
    '1 ação bônus',
    '9 metros',
    'V, S, M (um pequeno espelho de prata)',
    '1 minuto',
    'cl',
    'Quem quiser atacar a criatura protegida faz antes salvaguarda de Sabedoria ou escolhe outro alvo. Termina se ela atacar ou conjurar uma magia contra um inimigo.',
  ],
  [
    'Escudo',
    'abj',
    '1 reação',
    'Pessoal',
    'V, S',
    '1 rodada',
    'fe ma',
    'Quando for atingido por um ataque ou alvo de Mísseis Mágicos, você ganha +5 de CA até o início do seu próximo turno e nenhum dano de Mísseis Mágicos.',
  ],
  [
    'Escudo da Fé',
    'abj',
    '1 ação bônus',
    '18 metros',
    'V, S, M (um pequeno pergaminho com texto sagrado)',
    'Concentração, até 10 minutos',
    'cl pa',
    'Um campo cintilante dá +2 de CA a uma criatura.',
  ],
  [
    'Imagem Silenciosa',
    'ilu',
    '1 ação',
    '18 metros',
    'V, S, M (um pouco de lã)',
    'Concentração, até 10 minutos',
    'ba fe ma',
    'Cria uma imagem de objeto, criatura ou fenômeno em um cubo de 4,5 metros, sem som, cheiro ou temperatura. Investigação a desmascara.',
  ],
  [
    'Sono',
    'enc',
    '1 ação',
    '27 metros',
    'V, S, M (um punhado de areia fina, pétalas de rosa ou um grilo)',
    '1 minuto',
    'ba fe ma',
    'Joga 5d8 PV de criaturas, das de menos PV para as de mais, em sono mágico (inconscientes). Mortos-vivos e imunes a encanto não são afetados.',
    '+2d8 por círculo acima do 1º.',
  ],
  [
    'Falar com Animais',
    'adi',
    '1 ação (ritual)',
    'Pessoal',
    'V, S',
    '10 minutos',
    'ba dr pt',
    'Você compreende e se comunica verbalmente com feras. O conhecimento delas é limitado ao que percebem.',
  ],
  [
    'Onda Trovejante',
    'evo',
    '1 ação',
    'Pessoal (cubo de 4,5 metros)',
    'V, S',
    'Instantânea',
    'ba dr fe ma',
    'Salvaguarda de Constituição: 2d8 de dano trovejante e empurra 3 metros na falha; metade do dano na passa. O estrondo é ouvido a 90 metros.',
    '+1d8 por círculo acima do 1º.',
  ],
  [
    'Servo Invisível',
    'con',
    '1 ação (ritual)',
    '18 metros',
    'V, S, M (um pedaço de barbante e madeira)',
    '1 hora',
    'ba bx ma',
    'Uma força invisível e sem mente realiza tarefas simples (carregar, limpar, servir). Não ataca e tem 1 PV.',
  ],
  [
    'Raio Bruxo',
    'evo',
    '1 ação',
    '9 metros',
    'V, S, M (um galho de árvore atingida por raio)',
    'Concentração, até 1 minuto',
    'bx fe ma',
    'Um raio elétrico causa 1d12 de dano (ataque de magia à distância) e, nos turnos seguintes, você pode gastar uma ação para causar 1d12 de dano automático.',
    '+1d12 no dano inicial por círculo acima do 1º.',
  ],
  [
    'Armadura de Agathys',
    'abj',
    '1 ação',
    'Pessoal',
    'V, S, M (uma xícara de água)',
    '1 hora',
    'bx',
    'Você ganha 5 PV temporários; quando uma criatura o atinge corpo a corpo enquanto eles durarem, ela sofre 5 de dano de gelo.',
    '+5 PV temporários e +5 de dano por círculo acima do 1º.',
  ],
  [
    'Braços de Hadar',
    'con',
    '1 ação',
    'Pessoal (esfera de 3 metros)',
    'V, S',
    'Instantânea',
    'bx',
    'Tentáculos de energia sombria: salvaguarda de Força, 2d6 de dano necrótico e a criatura não pode usar reações; metade do dano ao passar.',
    '+1d6 por círculo acima do 1º.',
  ],
  [
    'Sussurros Dissonantes',
    'enc',
    '1 ação',
    '18 metros',
    'V',
    'Instantânea',
    'ba bx',
    'Uma melodia dolorosa: salvaguarda de Sabedoria, 3d6 de dano psíquico e a criatura usa a reação para se afastar; metade do dano ao passar.',
    '+1d6 por círculo acima do 1º.',
  ],
  [
    'Maldição Bruxa',
    'enc',
    '1 ação bônus',
    '27 metros',
    'V, S, M (o olho petrificado de um tritão)',
    'Concentração, até 1 hora',
    'bx',
    'Você amaldiçoa uma criatura: causa 1d6 de dano necrótico extra com ataques contra ela e ela tem desvantagem em testes de um atributo escolhido.',
    'Duração maior em círculos mais altos.',
  ],
  [
    'Golpe Enredante',
    'con',
    '1 ação bônus',
    'Pessoal',
    'V',
    'Concentração, até 1 minuto',
    'pt',
    'No próximo acerto com arma, vinhas prendem o alvo (Força) e causam 1d6 de dano perfurante por turno.',
    '+1d6 por círculo acima do 1º.',
  ],
  [
    'Chuva de Espinhos',
    'con',
    '1 ação bônus',
    'Pessoal',
    'V',
    'Concentração, até 1 minuto',
    'pt',
    'No próximo acerto com arma à distância, o projétil se transforma em chuva de espinhos: 1d10 de dano perfurante no alvo e 1d10 em criaturas a até 1,5 metro (Destreza).',
    '+1d10 por círculo acima do 1º.',
  ],
  [
    'Duelo Compelido',
    'enc',
    '1 ação bônus',
    '9 metros',
    'V',
    'Concentração, até 1 minuto',
    'pa',
    'Uma criatura faz salvaguarda de Sabedoria ou fica compelida a lutar só com você, com desvantagem ao atacar outros, e não consegue se afastar de você voluntariamente.',
  ],
  [
    'Golpe Ardente',
    'evo',
    '1 ação bônus',
    'Pessoal',
    'V',
    'Concentração, até 1 minuto',
    'pa',
    'No próximo acerto com arma corpo a corpo, o ataque causa 1d6 de dano de fogo extra e o alvo pega fogo.',
    '+1d6 por círculo acima do 1º.',
  ],
  [
    'Golpe Trovejante',
    'evo',
    '1 ação bônus',
    'Pessoal',
    'V',
    'Concentração, até 1 minuto',
    'pa',
    'No próximo acerto com arma corpo a corpo, 2d6 de dano trovejante extra; o alvo faz salvaguarda de Força ou é empurrado 3 metros e cai.',
  ],
  [
    'Golpe Colérico',
    'evo',
    '1 ação bônus',
    'Pessoal',
    'V',
    'Concentração, até 1 minuto',
    'pa',
    'No próximo acerto com arma corpo a corpo, 1d6 de dano psíquico extra e o alvo faz salvaguarda de Sabedoria ou fica amedrontado.',
  ],
  [
    'Raio Doentio',
    'nec',
    '1 ação',
    '18 metros',
    'V, S',
    'Instantânea',
    'fe ma',
    'Raio esverdeado: ataque de magia à distância causa 2d8 de dano de veneno e o alvo faz salvaguarda de Constituição ou fica envenenado até o fim do seu próximo turno.',
    '+1d8 por círculo acima do 1º.',
  ],
  [
    'Orbe Cromático',
    'evo',
    '1 ação',
    '27 metros',
    'V, S, M (um diamante de 50 po)',
    'Instantânea',
    'fe ma',
    'Esfera de energia (ácido, frio, fogo, elétrico, veneno ou trovejante, à sua escolha): ataque de magia à distância causa 3d8 de dano do tipo.',
    '+1d8 por círculo acima do 1º.',
  ],
  [
    'Disco Flutuante de Tenser',
    'con',
    '1 ação (ritual)',
    '9 metros',
    'V, S, M (uma gota de mercúrio)',
    '1 hora',
    'ma',
    'Cria um disco horizontal de força que carrega até 250 kg e segue você a até 6 metros de altura sobre o chão.',
  ],
];
