import type { SpellRow } from './types';

export const C2: readonly SpellRow[] = [
  [
    'Auxílio',
    'abj',
    '1 ação',
    '9 metros',
    'V, S, M (uma tira de pano branco)',
    '8 horas',
    'cl pa',
    'Até três criaturas aumentam o máximo de PV e os PV atuais em 5 por 8 horas.',
    '+5 PV por círculo acima do 2º.',
  ],
  [
    'Alterar-se',
    'tra',
    '1 ação',
    'Pessoal',
    'V, S',
    'Concentração, até 1 hora',
    'fe ma',
    'Você escolhe: adaptar-se ao meio aquático, mudar a aparência ou criar armas naturais (1d6 de dano, contam como mágicas).',
  ],
  [
    'Mensageiro Animal',
    'enc',
    '1 ação (ritual)',
    '9 metros',
    'V, S, M (um pouco de comida)',
    '24 horas',
    'ba dr pt',
    'Uma fera Miúda leva uma mensagem de até 25 palavras a um destino que você descreva, a até 40 km por dia.',
    '+48 horas por círculo acima do 2º.',
  ],
  [
    'Tranca Arcana',
    'abj',
    '1 ação',
    'Toque',
    'V, S, M (pó de ouro no valor de 25 po)',
    'Até ser dissipada',
    'ma',
    'Tranca magicamente uma porta, janela ou recipiente. Você e quem você indicar abrem normalmente; os demais precisam de Arrombar, Dissipar Magia ou Nulificar.',
  ],
  [
    'Aura Mágica do Arcanista',
    'ilu',
    '1 ação',
    'Toque',
    'V, S, M (um pequeno quadrado de seda)',
    '24 horas',
    'ma',
    'Disfarça a aura de um item ou criatura para que ela pareça de outra escola ou natureza, ou esconde magia de detecção.',
  ],
  [
    'Augúrio',
    'adi',
    '1 minuto (ritual)',
    'Pessoal',
    'V, S, M (varetas, ossos ou fichas com marcas especiais, no valor de 25 po)',
    'Instantânea',
    'cl',
    'Você pergunta sobre um acontecimento nos próximos 30 minutos e recebe um presságio: bom, ruim, ambos ou nenhum.',
  ],
  [
    'Pele de Árvore',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (um punhado de casca de carvalho)',
    'Concentração, até 1 hora',
    'dr pt',
    'A pele da criatura tocada fica rígida: sua CA não pode ser inferior a 16 enquanto durar.',
  ],
  [
    'Sentidos Animais',
    'adi',
    '1 ação (ritual)',
    'Toque',
    'S',
    'Concentração, até 1 hora',
    'dr pt',
    'Você usa os sentidos de uma fera voluntária tocada, enquanto fica cego e surdo ao próprio ambiente.',
  ],
  [
    'Cegueira/Surdez',
    'nec',
    '1 ação',
    '9 metros',
    'V',
    '1 minuto',
    'ba cl fe ma',
    'Uma criatura faz salvaguarda de Constituição ou fica cega ou surda (sua escolha). Repete ao fim de cada turno.',
    'Uma criatura adicional por círculo acima do 2º.',
  ],
  [
    'Borrão',
    'ilu',
    '1 ação',
    'Pessoal',
    'V',
    'Concentração, até 1 minuto',
    'fe ma',
    'Sua imagem fica difusa: atacantes têm desvantagem nas jogadas de ataque contra você, a menos que não dependam de visão.',
  ],
  [
    'Golpe Marcador',
    'evo',
    '1 ação bônus',
    'Pessoal',
    'V',
    'Concentração, até 1 minuto',
    'pa',
    'No próximo acerto com arma, 2d6 de dano radiante extra; o alvo fica visível se invisível e brilha, sem poder se esconder.',
    '+1d6 por círculo acima do 2º.',
  ],
  [
    'Acalmar Emoções',
    'enc',
    '1 ação',
    '18 metros',
    'V, S, M (um gesto de calma)',
    'Concentração, até 1 minuto',
    'ba cl',
    'Criaturas em uma esfera de 6 metros de raio fazem salvaguarda de Carisma. Você suprime encanto e medo, ou torna criaturas indiferentes a quem lhes for hostil.',
  ],
  [
    'Nuvem de Adagas',
    'con',
    '1 ação',
    '18 metros',
    'V, S, M (um caco de vidro)',
    'Concentração, até 1 minuto',
    'ba bx fe ma',
    'Adagas giratórias em um cubo de 1,5 metro: 4d4 de dano cortante a quem entrar ou começar o turno ali.',
    '+2d4 por círculo acima do 2º.',
  ],
  [
    'Chama Contínua',
    'evo',
    '1 ação',
    'Toque',
    'V, S, M (pó de rubi no valor de 50 po)',
    'Até ser dissipada',
    'cl ma',
    'Uma chama sem calor, luminosa como tocha, surge de um objeto tocado.',
  ],
  [
    'Cordão de Flechas',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (quatro ou mais flechas ou virotes)',
    '8 horas',
    'pt',
    'Você carrega quatro projéteis; quando uma criatura entra em 9 metros deles sem ser autorizada, um projétil a atinge: 1d6 de dano perfurante (Destreza evita).',
    '+2 projéteis por círculo acima do 2º.',
  ],
  [
    'Coroa da Loucura',
    'enc',
    '1 ação',
    '36 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'ba bx fe ma',
    'Um humanoide faz salvaguarda de Sabedoria ou fica enfeitiçado, atacando uma criatura que você escolher no turno dele. Ele repete a salvaguarda ao fim de cada turno.',
  ],
  [
    'Escuridão',
    'evo',
    '1 ação',
    '18 metros',
    'V, M (pelo de morcego e uma gota de piche)',
    'Concentração, até 10 minutos',
    'bx fe ma',
    'Esfera de 4,5 metros de raio de trevas mágicas que bloqueiam até a visão no escuro e luz de magias de 2º círculo ou menos.',
  ],
  [
    'Visão no Escuro',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (uma cenoura seca)',
    '8 horas',
    'dr pt fe ma',
    'A criatura tocada ganha visão no escuro de 18 metros.',
  ],
  [
    'Detectar Pensamentos',
    'adi',
    '1 ação',
    'Pessoal',
    'V, S, M (uma moeda de cobre)',
    'Concentração, até 1 minuto',
    'ba fe ma',
    'Você lê pensamentos superficiais de criaturas a até 9 metros e, com mais concentração, sonda a mente de uma delas (Sabedoria resiste).',
  ],
  [
    'Aprimorar Atributo',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (pelo ou pena de um animal)',
    'Concentração, até 1 hora',
    'ba cl dr fe',
    'A criatura tocada ganha um benefício: vantagem em testes de um atributo, conforme o efeito escolhido (Astúcia da Raposa, Força do Touro, Elegância do Gato etc.).',
    'Uma criatura adicional por círculo acima do 2º.',
  ],
  [
    'Aumentar/Reduzir',
    'tra',
    '1 ação',
    '9 metros',
    'V, S, M (uma pitada de pó de ferro)',
    'Concentração, até 1 minuto',
    'fe ma',
    'Uma criatura ou objeto aumenta ou diminui uma categoria de tamanho: +1d4 de dano e vantagem em Força (aumentar) ou −1d4 e desvantagem (reduzir).',
  ],
  [
    'Encantar',
    'enc',
    '1 ação',
    '18 metros',
    'V, S',
    '1 minuto',
    'ba bx',
    'Criaturas à sua escolha que o veem fazem salvaguarda de Sabedoria ou ficam fascinadas, ignorando tudo ao redor.',
  ],
  [
    'Convocar Montaria',
    'con',
    '10 minutos',
    '9 metros',
    'V, S',
    'Instantânea',
    'pa',
    'Convoca um espírito que assume a forma de uma montaria fiel (cavalo, pônei, camelo, alce, mastim), com laço telepático. Se reduzida a 0 PV, desaparece.',
  ],
  [
    'Encontrar Armadilhas',
    'adi',
    '1 ação',
    '36 metros',
    'V, S',
    'Instantânea',
    'cl dr pt',
    'Você sente a presença de armadilhas na linha de visão, sem revelar sua natureza ou localização exata.',
  ],
  [
    'Lâmina de Fogo',
    'evo',
    '1 ação bônus',
    'Pessoal',
    'V, S, M (folha de sumagre)',
    'Concentração, até 10 minutos',
    'dr',
    'Uma lâmina flamejante na sua mão causa 3d6 de dano de fogo (ataque de magia corpo a corpo) e ilumina 3 metros.',
    '+1d6 a cada 2 círculos acima do 2º.',
  ],
  [
    'Esfera Flamejante',
    'con',
    '1 ação',
    '18 metros',
    'V, S, M (sebo, enxofre e pó de ferro)',
    'Concentração, até 1 minuto',
    'dr ma',
    'Esfera de fogo de 1,5 metro rola pelo chão e causa 2d6 de dano de fogo (Destreza) a criaturas adjacentes.',
    '+1d6 por círculo acima do 2º.',
  ],
  [
    'Repouso Tranquilo',
    'nec',
    '1 ação (ritual)',
    'Toque',
    'V, S, M (uma pitada de sal e uma moeda de cobre sobre cada olho)',
    '10 dias',
    'cl ma',
    'Um cadáver não pode virar morto-vivo, e o tempo para ressurreição não corre durante a duração.',
  ],
  [
    'Lufada de Vento',
    'evo',
    '1 ação',
    'Pessoal (linha de 18 metros)',
    'V, S, M (uma semente de legume)',
    'Concentração, até 1 minuto',
    'dr fe ma',
    'Linha de vento forte: criaturas fazem salvaguarda de Força ou são empurradas 4,5 metros; voo e chamas são prejudicados.',
  ],
  [
    'Esquentar Metal',
    'tra',
    '1 ação',
    '18 metros',
    'V, S, M (um pedaço de ferro e uma chama)',
    'Concentração, até 1 minuto',
    'ba dr',
    'Um objeto de metal fica incandescente: 2d8 de dano de fogo a quem o segurar, com desvantagem em ataques e testes se não o largar. Bônus de ação para repetir.',
    '+1d8 por círculo acima do 2º.',
  ],
  [
    'Imobilizar Pessoa',
    'enc',
    '1 ação',
    '18 metros',
    'V, S, M (um pequeno pedaço de ferro reto)',
    'Concentração, até 1 minuto',
    'ba cl dr fe bx ma',
    'Um humanoide faz salvaguarda de Sabedoria ou fica paralisado, repetindo ao fim de cada turno.',
    'Uma criatura adicional por círculo acima do 2º.',
  ],
  [
    'Invisibilidade',
    'ilu',
    '1 ação',
    'Toque',
    'V, S, M (um cílio coberto de goma-arábica)',
    'Concentração, até 1 hora',
    'ba bx fe ma',
    'A criatura tocada fica invisível até atacar ou conjurar uma magia.',
    'Uma criatura adicional por círculo acima do 2º.',
  ],
  [
    'Arrombar',
    'tra',
    '1 ação',
    '18 metros',
    'V',
    'Instantânea',
    'ba fe ma',
    'Abre uma tranca, porta, baú ou algemas, mas faz um estrondo audível a 90 metros.',
  ],
  [
    'Restauração Menor',
    'abj',
    '1 ação',
    'Toque',
    'V, S',
    'Instantânea',
    'ba cl dr pa pt',
    'Acaba com uma doença ou uma condição: cego, surdo, paralisado ou envenenado.',
  ],
  [
    'Levitação',
    'tra',
    '1 ação',
    '18 metros',
    'V, S, M (um pequeno anel de couro ou um fio de ouro)',
    'Concentração, até 10 minutos',
    'fe ma',
    'Uma criatura ou objeto (até 250 kg) levita até 6 metros e se move com sua ação a cada turno.',
  ],
  [
    'Localizar Animais ou Plantas',
    'adi',
    '1 ação (ritual)',
    'Pessoal',
    'V, S, M (um pouco de pelo de cão de caça)',
    'Instantânea',
    'ba dr pt',
    'Você descobre a direção e a distância do tipo mais próximo de animal ou planta que nomear, a até 8 km.',
  ],
  [
    'Localizar Objeto',
    'adi',
    '1 ação',
    'Pessoal',
    'V, S, M (um galho de vime)',
    'Concentração, até 10 minutos',
    'ba cl dr pa pt ma',
    'Você sente a direção de um objeto conhecido a até 300 metros.',
  ],
  [
    'Boca Mágica',
    'ilu',
    '1 minuto (ritual)',
    '9 metros',
    'V, S, M (um pouco de favo de mel e pó de jade no valor de 10 po)',
    'Até ser dissipada',
    'ba ma',
    'Implanta em um objeto uma mensagem de até 25 palavras, falada quando um gatilho definido acontecer.',
  ],
  [
    'Arma Mágica',
    'tra',
    '1 ação bônus',
    'Toque',
    'V, S',
    'Concentração, até 1 hora',
    'pa ma',
    'Uma arma não mágica vira mágica: +1 nos ataques e dano.',
    '+2 com círculo 4+ e +3 com círculo 6+.',
  ],
  [
    'Imagem Espelhada',
    'ilu',
    '1 ação',
    'Pessoal',
    'V, S',
    '1 minuto',
    'bx fe ma',
    'Três duplicatas ilusórias surgem; atacantes podem acertar uma duplicata (que some) em vez de você, conforme o número restante.',
  ],
  [
    'Passo Nebuloso',
    'con',
    '1 ação bônus',
    'Pessoal',
    'V',
    'Instantânea',
    'bx fe ma',
    'Você se teleporta até 9 metros para um espaço desocupado que você veja.',
  ],
  [
    'Raio de Luar',
    'evo',
    '1 ação',
    '36 metros',
    'V, S, M (algumas sementes de planta lunar e feldspato)',
    'Concentração, até 1 minuto',
    'dr',
    'Coluna de luz de 1,5 metro de raio: 2d10 de dano radiante (Constituição) a quem entrar ou começar o turno ali. Metamorfos têm desvantagem.',
    '+1d10 por círculo acima do 2º.',
  ],
  [
    'Passos sem Rastro',
    'abj',
    '1 ação',
    'Pessoal',
    'V, S, M (cinzas de folha de visco)',
    'Concentração, até 1 hora',
    'dr pt',
    'Você e seus aliados em 9 metros ganham +10 em testes de Furtividade e não deixam rastros.',
  ],
  [
    'Força Fantasmagórica',
    'ilu',
    '1 ação',
    '18 metros',
    'V, S, M (um tufo de lã de carneiro)',
    'Concentração, até 1 minuto',
    'ba fe bx ma',
    'Uma criatura faz salvaguarda de Inteligência ou percebe uma ilusão que lhe causa 1d6 de dano psíquico por turno.',
  ],
  [
    'Prece de Cura',
    'evo',
    '10 minutos',
    '9 metros',
    'V',
    'Instantânea',
    'cl',
    'Até seis criaturas recuperam 2d8 + seu modificador de atributo de conjuração em PV.',
    '+1d8 por círculo acima do 2º.',
  ],
  [
    'Proteção Contra Veneno',
    'abj',
    '1 ação',
    'Toque',
    'V, S',
    '1 hora',
    'cl dr pa pt',
    'Neutraliza um veneno na criatura tocada; ela tem vantagem em salvaguardas contra ser envenenada e resistência a dano de veneno.',
  ],
  [
    'Raio do Enfraquecimento',
    'nec',
    '1 ação',
    '18 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'bx ma',
    'Um ataque de magia à distância faz o alvo causar metade do dano em ataques com Força; o alvo repete a salvaguarda de Constituição a cada turno.',
  ],
  [
    'Truque da Corda',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (extrato de milho em pó e um laço de pergaminho)',
    '1 hora',
    'ma',
    'Uma corda sobe e cria um espaço extradimensional de 3 metros por 6 metros, onde até oito criaturas se escondem.',
  ],
  [
    'Raio Ardente',
    'evo',
    '1 ação',
    '36 metros',
    'V, S',
    'Instantânea',
    'fe ma',
    'Três raios de fogo; cada um é um ataque de magia à distância que causa 2d6 de dano de fogo.',
    '+1 raio por círculo acima do 2º.',
  ],
  [
    'Ver Invisibilidade',
    'adi',
    '1 ação',
    'Pessoal',
    'V, S, M (um pouco de talco e prata em pó)',
    '1 hora',
    'ba fe ma',
    'Você enxerga criaturas e objetos invisíveis e o Plano Etéreo, que parecem translúcidos.',
  ],
  [
    'Despedaçar',
    'evo',
    '1 ação',
    '18 metros',
    'V, S, M (um chip de mica)',
    'Instantânea',
    'ba bx fe ma',
    'Ruído doloroso em uma esfera de 3 metros: 3d8 de dano trovejante (Constituição); criaturas inorgânicas têm desvantagem na salvaguarda.',
    '+1d8 por círculo acima do 2º.',
  ],
  [
    'Silêncio',
    'ilu',
    '1 ação (ritual)',
    '36 metros',
    'V, S',
    'Concentração, até 10 minutos',
    'ba cl pt',
    'Em uma esfera de 6 metros de raio nenhum som existe: criaturas ficam imunes a dano trovejante e surdas, e não se pode conjurar magias com componente verbal.',
  ],
  [
    'Escalar Paredes',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (uma gota de betume e uma aranha)',
    'Concentração, até 1 hora',
    'fe bx ma',
    'Uma criatura tocada ganha deslocamento de escalada igual ao deslocamento e pode andar em paredes e tetos.',
  ],
  [
    'Crescimento de Espinhos',
    'tra',
    '1 ação',
    '45 metros',
    'V, S, M (sete espinhos ou sete raminhos pontiagudos)',
    'Concentração, até 10 minutos',
    'dr pt',
    'Área de 6 metros de raio fica coberta de espinhos disfarçados: 2d4 de dano perfurante a cada 1,5 metro percorrido.',
  ],
  [
    'Arma Espiritual',
    'evo',
    '1 ação bônus',
    '18 metros',
    'V, S',
    '1 minuto',
    'cl',
    'Uma arma espectral ataca (ataque de magia corpo a corpo): 1d8 + modificador de conjuração de dano de força. Ação bônus para mover e atacar.',
    '+1d8 a cada 2 círculos acima do 2º.',
  ],
  [
    'Sugestão',
    'enc',
    '1 ação',
    '9 metros',
    'V, M (uma língua de cobra e uma gota de mel)',
    'Concentração, até 8 horas',
    'ba bx fe ma',
    'Você sugere uma ação razoável de uma ou duas frases; a criatura faz salvaguarda de Sabedoria ou a segue.',
  ],
  [
    'Teia',
    'con',
    '1 ação',
    '18 metros',
    'V, S, M (um pouco de teia de aranha)',
    'Concentração, até 1 hora',
    'fe ma',
    'Teias em um cubo de 6 metros: criaturas fazem salvaguarda de Destreza ou ficam impedidas. As teias são inflamáveis.',
  ],
  [
    'Vínculo de Proteção',
    'abj',
    '1 ação',
    'Toque',
    'V, S, M (um par de anéis de platina, 50 po cada)',
    '1 hora',
    'cl pa',
    'A criatura tocada ganha +1 CA e salvaguardas, e resistência a todo dano, mas você sofre o mesmo dano que ela recebe.',
  ],
  [
    'Zona da Verdade',
    'enc',
    '1 ação',
    '18 metros',
    'V, S',
    '10 minutos',
    'ba cl pa',
    'Criaturas em uma esfera de 4,5 metros de raio fazem salvaguarda de Carisma ou não conseguem mentir. Você sabe quem passou.',
  ],
  [
    'Flecha Ácida de Melf',
    'evo',
    '1 ação',
    '27 metros',
    'V, S, M (ruibarbo em pó e uma língua de víbora)',
    'Instantânea',
    'ma',
    'Ataque de magia à distância: 4d4 de dano ácido e 2d4 no fim do próximo turno do alvo; se errar, metade no primeiro dano.',
    '+1d4 nos dois danos por círculo acima do 2º.',
  ],
];
