import type { SpellRow } from './types';

export const C3: readonly SpellRow[] = [
  [
    'Reanimar Mortos',
    'nec',
    '1 minuto',
    '3 metros',
    'V, S, M (uma gota de sangue, um pedaço de carne e uma pitada de pó de osso)',
    'Instantânea',
    'cl ma',
    'Anima um esqueleto ou zumbi de um corpo de criatura Média ou Pequena sob seu comando por 24 horas (renovável).',
    '+2 mortos-vivos por círculo acima do 3º.',
  ],
  [
    'Farol de Esperança',
    'abj',
    '1 ação',
    '9 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'cl',
    'Criaturas à sua escolha têm vantagem em salvaguardas de Sabedoria e contra a morte, e recuperam o máximo de PV ao serem curadas.',
  ],
  [
    'Rogar Maldição',
    'nec',
    '1 ação',
    'Toque',
    'V, S',
    'Concentração, até 1 minuto',
    'ba cl ma',
    'Uma criatura faz salvaguarda de Sabedoria ou sofre uma maldição à sua escolha: desvantagem em um atributo, em ataques contra você, perde ações, ou 1d8 de dano necrótico extra.',
    'Duração maior em círculos mais altos.',
  ],
  [
    'Golpe Cegante',
    'evo',
    '1 ação bônus',
    'Pessoal',
    'V',
    'Concentração, até 1 minuto',
    'pa',
    'No próximo acerto com arma corpo a corpo, 3d8 de dano radiante extra e o alvo faz salvaguarda de Constituição ou fica cego.',
  ],
  [
    'Piscar',
    'tra',
    '1 ação',
    'Pessoal',
    'V, S',
    '1 minuto',
    'fe ma',
    'No fim de cada um dos seus turnos, role 1d20; com 11 ou mais, você some para o Plano Etéreo e reaparece no próximo turno em outro espaço próximo.',
  ],
  [
    'Convocar Relâmpago',
    'con',
    '1 ação',
    '36 metros',
    'V, S',
    'Concentração, até 10 minutos',
    'dr',
    'Uma nuvem de tempestade surge; a cada turno você pode fazer cair um raio de 3 metros de raio causando 3d10 de dano elétrico (Destreza reduz à metade).',
    '+1d10 por círculo acima do 3º.',
  ],
  [
    'Clarividência',
    'adi',
    '10 minutos',
    '1,5 quilômetro',
    'V, S, M (um foco no valor de 100 po)',
    'Concentração, até 10 minutos',
    'ba cl fe bx ma',
    'Cria um sensor invisível em um local conhecido ou óbvio; você vê ou ouve através dele.',
  ],
  [
    'Conjurar Animais',
    'con',
    '1 ação',
    '18 metros',
    'V, S',
    'Concentração, até 1 hora',
    'dr pt',
    'Convoca espíritos de feras de ND 1/4 ou menor (1 fera de ND 2, 2 de ND 1, 4 de ND 1/2, ou 8 de ND 1/4) que obedecem a você.',
    'Mais feras com círculos 5, 7 e 9.',
  ],
  [
    'Conjurar Barragem',
    'con',
    '1 ação',
    'Pessoal (cone de 18 metros)',
    'V, S, M (uma munição ou uma arma de arremesso)',
    'Instantânea',
    'pt',
    'Muitas cópias da munição surgem em um cone: 3d8 de dano (Destreza reduz à metade), do mesmo tipo da arma.',
  ],
  [
    'Contramágica',
    'abj',
    '1 reação',
    '18 metros',
    'S',
    'Instantânea',
    'bx fe ma',
    'Interrompe uma magia de 3º círculo ou menor. Magia de círculo maior exige um teste de atributo de conjuração (CD 10 + círculo).',
    'Interrompe automaticamente magias do círculo usado ou menor.',
  ],
  [
    'Criar Alimentos',
    'con',
    '1 ação',
    '9 metros',
    'V, S',
    'Instantânea',
    'cl pa',
    'Cria 45 kg de comida e 120 litros de água, suficientes para 15 humanoides ou 5 montarias por 24 horas.',
  ],
  [
    'Manto do Cruzado',
    'evo',
    '1 ação',
    'Pessoal',
    'V',
    'Concentração, até 1 minuto',
    'pa',
    'Aura de 9 metros: você e as criaturas à sua escolha causam 1d4 de dano radiante extra com ataques com arma.',
  ],
  [
    'Luz do Dia',
    'evo',
    '1 ação',
    '18 metros',
    'V, S',
    '1 hora',
    'cl dr pa pt fe',
    'Esfera de luz plena de 18 metros de raio e penumbra por mais 18 metros; dissipa escuridão mágica de 3º círculo ou menor.',
  ],
  [
    'Dissipar Magia',
    'abj',
    '1 ação',
    '36 metros',
    'V, S',
    'Instantânea',
    'ba cl dr pa fe bx ma',
    'Encerra magias de 3º círculo ou menor num alvo; para círculos maiores, teste de atributo de conjuração (CD 10 + círculo).',
    'Encerra automaticamente magias do círculo usado ou menor.',
  ],
  [
    'Arma Elemental',
    'tra',
    '1 ação',
    'Toque',
    'V, S',
    'Concentração, até 1 hora',
    'pa',
    'Uma arma tocada vira mágica: +1 nos ataques e 1d4 de dano de ácido, frio, fogo, elétrico ou trovejante extra.',
    '+2 e +3 com círculos 5 e 7.',
  ],
  [
    'Medo',
    'ilu',
    '1 ação',
    'Pessoal (cone de 9 metros)',
    'V, S, M (uma pena branca ou o coração de uma galinha)',
    'Concentração, até 1 minuto',
    'ba bx fe ma',
    'Criaturas no cone fazem salvaguarda de Sabedoria ou largam o que seguram e ficam amedrontadas, fugindo de você.',
  ],
  [
    'Fingir de Morto',
    'nec',
    '1 ação (ritual)',
    'Toque',
    'V, S, M (pó de gesso)',
    '1 hora',
    'ba cl dr ma',
    'Uma criatura voluntária parece morta, fica cega, incapacitada e com resistência a todo dano (menos psíquico). Ainda sofre doenças e veneno como se morta.',
  ],
  [
    'Bola de Fogo',
    'evo',
    '1 ação',
    '45 metros',
    'V, S, M (uma bolinha de guano de morcego e enxofre)',
    'Instantânea',
    'fe ma',
    'Explosão de 6 metros de raio: 8d6 de dano de fogo (Destreza reduz à metade). Incendeia objetos inflamáveis soltos.',
    '+1d6 por círculo acima do 3º.',
  ],
  [
    'Voo',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (uma pena de asa de qualquer pássaro)',
    'Concentração, até 10 minutos',
    'fe bx ma',
    'A criatura tocada ganha deslocamento de voo de 18 metros.',
    'Uma criatura adicional por círculo acima do 3º.',
  ],
  [
    'Forma Gasosa',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (um pouco de gaze e fumaça)',
    'Concentração, até 1 hora',
    'fe bx ma',
    'Uma criatura voluntária vira uma nuvem de gás, com deslocamento de voo de 3 metros e resistência a dano não mágico. Não pode falar nem conjurar.',
  ],
  [
    'Glifo de Proteção',
    'abj',
    '1 hora',
    'Toque',
    'V, S, M (incenso e pó de diamante no valor de 200 po)',
    'Até ser dissipada ou ativada',
    'ba cl ma',
    'Grava um glifo em uma superfície; ao ser ativado, explode (5d8 de dano de um tipo) ou libera uma magia de 3º círculo ou menor.',
    '+1d8 de dano ou +1 círculo por círculo acima do 3º.',
  ],
  [
    'Velocidade',
    'tra',
    '1 ação',
    '9 metros',
    'V, S, M (uma raspa de raiz de alcaçuz)',
    'Concentração, até 1 minuto',
    'fe ma',
    'Uma criatura dobra o deslocamento, ganha +2 de CA, vantagem em Destreza e uma ação extra limitada. Ao fim, fica letárgica por 1 rodada.',
  ],
  [
    'Fome de Hadar',
    'con',
    '1 ação',
    '45 metros',
    'V, S, M (um tentáculo em conserva)',
    'Concentração, até 1 minuto',
    'bx',
    'Esfera de 6 metros de vazio escuro: 2d6 de dano de gelo a quem começar o turno ali e 2d6 de dano ácido se terminar o turno.',
  ],
  [
    'Padrão Hipnótico',
    'ilu',
    '1 ação',
    '36 metros',
    'S, M (um bastão de incenso aceso ou um vidro de cristal)',
    'Concentração, até 1 minuto',
    'ba bx fe ma',
    'Criaturas em um cubo de 9 metros fazem salvaguarda de Sabedoria ou ficam enfeitiçadas, incapacitadas e com deslocamento 0.',
  ],
  [
    'Cabana Minúscula de Leomund',
    'evo',
    '1 minuto (ritual)',
    'Pessoal (hemisfério de 3 metros)',
    'V, S, M (uma pequena conta de cristal)',
    '8 horas',
    'ba ma',
    'Uma cúpula protegida contra o clima e invasores: nada atravessa. Até nove criaturas Médias descansam no interior.',
  ],
  [
    'Relâmpago',
    'evo',
    '1 ação',
    'Pessoal (linha de 30 metros)',
    'V, S, M (um pouco de pelo e uma barra de âmbar, cristal ou vidro)',
    'Instantânea',
    'fe ma',
    'Raio de 30 metros por 1,5 de largura: 8d6 de dano elétrico (Destreza reduz à metade). Acende objetos inflamáveis.',
    '+1d6 por círculo acima do 3º.',
  ],
  [
    'Círculo Mágico',
    'abj',
    '1 minuto',
    '3 metros',
    'V, S, M (água benta ou pó de prata e ferro no valor de 100 po)',
    '1 hora',
    'cl pa bx ma',
    'Cilindro de 3 metros de raio: um tipo de criatura (celestiais, elementais, fadas, corruptores, mortos-vivos) não entra, não afeta nem possui quem está dentro.',
    '+1 hora por círculo acima do 3º.',
  ],
  [
    'Imagem Maior',
    'ilu',
    '1 ação',
    '36 metros',
    'V, S, M (um pouco de lã)',
    'Concentração, até 10 minutos',
    'ba bx fe ma',
    'Imagem de um objeto, criatura ou fenômeno em um cubo de 6 metros, com som, cheiro e temperatura. A magia se mantém se você a mover.',
    'Duração de 24 horas sem concentração no 6º círculo ou mais.',
  ],
  [
    'Palavra de Cura em Massa',
    'evo',
    '1 ação bônus',
    '18 metros',
    'V',
    'Instantânea',
    'cl',
    'Até seis criaturas recuperam 1d4 + modificador de conjuração em PV.',
    '+1d4 por círculo acima do 3º.',
  ],
  [
    'Fundir-se às Rochas',
    'tra',
    '1 ação (ritual)',
    'Toque',
    'V, S',
    '8 horas',
    'cl dr',
    'Você entra em uma rocha grande o bastante para conter seu corpo. Fica escondido, mas ainda ouve e vê com visão ao redor da pedra.',
  ],
  [
    'Antidetecção',
    'abj',
    '1 ação',
    'Toque',
    'V, S, M (uma pitada de pó de diamante, 25 po)',
    '8 horas',
    'ba pt ma',
    'Esconde uma criatura ou objeto de adivinhação e de sensores mágicos.',
  ],
  [
    'Montaria Fantasma',
    'ilu',
    '1 minuto (ritual)',
    '9 metros',
    'V, S',
    '1 hora',
    'ma',
    'Cria um cavalo quase real (deslocamento 30 m, anda sobre água) que carrega você e até outros três passageiros. Some se sofrer dano.',
  ],
  [
    'Crescimento de Plantas',
    'tra',
    '1 ação ou 8 horas',
    '45 metros',
    'V, S',
    'Instantânea',
    'ba dr pt',
    'Enriquece plantas num raio de 30 metros por 1 ano, ou torna a vegetação densa e intransponível num raio de 30 metros (terreno difícil).',
  ],
  [
    'Proteção Contra Energia',
    'abj',
    '1 ação',
    'Toque',
    'V, S',
    'Concentração, até 1 hora',
    'cl dr pt fe ma',
    'A criatura tocada ganha resistência a ácido, frio, fogo, elétrico ou trovejante, à sua escolha.',
  ],
  [
    'Remover Maldição',
    'abj',
    '1 ação',
    'Toque',
    'V, S',
    'Instantânea',
    'cl pa bx ma',
    'Acaba com todas as maldições sobre uma criatura ou objeto tocado. Não remove a maldição de um item mágico, apenas quebra a sintonização.',
  ],
  [
    'Revivificar',
    'con',
    '1 ação',
    'Toque',
    'V, S, M (diamantes no valor de 300 po, consumidos)',
    'Instantânea',
    'cl pa',
    'Uma criatura que morreu nos últimos 1 minuto volta à vida com 1 PV. Não restaura partes do corpo perdidas.',
  ],
  [
    'Mensagem à Distância',
    'evo',
    '1 ação',
    'Ilimitada',
    'V, S, M (um pedaço de fio de cobre)',
    '1 rodada',
    'cl ba ma',
    'Você envia uma mensagem de 25 palavras a uma criatura que conheça; ela responde com 25 palavras. Funciona entre planos, mas não sem a menção precisa.',
  ],
  [
    'Chuva de Gelo',
    'con',
    '1 ação',
    '45 metros',
    'V, S, M (uma pitada de poeira e algumas gotas de água)',
    'Concentração, até 1 minuto',
    'dr fe ma',
    'Cilindro de 12 metros de raio onde a chuva congela: terreno difícil escorregadio, visão pesadamente obscurecida e chamas apagadas.',
  ],
  [
    'Lentidão',
    'tra',
    '1 ação',
    '36 metros',
    'V, S, M (uma gota de melaço)',
    'Concentração, até 1 minuto',
    'fe ma',
    'Até seis criaturas fazem salvaguarda de Sabedoria ou ficam lentas: deslocamento reduzido pela metade, −2 de CA e Destreza, uma ação ou ação bônus por turno.',
  ],
  [
    'Falar com os Mortos',
    'nec',
    '1 ação',
    '3 metros',
    'V, S, M (incenso queimado)',
    '10 minutos',
    'ba cl',
    'Um cadáver responde a até cinco perguntas, com o conhecimento que tinha em vida, mas não conta o que não sabia nem o futuro.',
  ],
  [
    'Falar com Plantas',
    'tra',
    '1 ação',
    'Pessoal (raio de 9 metros)',
    'V, S',
    '10 minutos',
    'ba dr pt',
    'Você conversa com plantas, que podem mudar de lugar o terreno difícil ou revelar o que viram. Elas também abrem passagem se você pedir.',
  ],
  [
    'Guardiões Espirituais',
    'con',
    '1 ação',
    'Pessoal (raio de 4,5 metros)',
    'V, S, M (um símbolo sagrado)',
    'Concentração, até 10 minutos',
    'cl',
    'Espíritos voam ao seu redor: criaturas escolhidas por você têm deslocamento reduzido pela metade e sofrem 3d8 de dano radiante ou necrótico (Sabedoria reduz à metade) no início do turno ou ao entrar.',
    '+1d8 por círculo acima do 3º.',
  ],
  [
    'Nuvem Fétida',
    'con',
    '1 ação',
    '27 metros',
    'V, S, M (um ovo podre ou repolho-fedorento)',
    'Concentração, até 1 minuto',
    'ba fe ma',
    'Esfera de 6 metros de gás: criaturas fazem salvaguarda de Constituição ou passam o turno enjoadas, sem agir.',
  ],
  [
    'Línguas',
    'adi',
    '1 ação',
    'Toque',
    'V, M (um pequeno modelo de argila de uma torre)',
    '1 hora',
    'ba cl bx fe ma',
    'A criatura tocada entende qualquer idioma falado e, ao falar, é entendida por qualquer criatura que conheça uma língua.',
  ],
  [
    'Toque Vampírico',
    'nec',
    '1 ação',
    'Pessoal',
    'V, S',
    'Concentração, até 1 minuto',
    'bx ma',
    'Ataque de magia corpo a corpo: 3d6 de dano necrótico, e você recupera metade em PV. Pode repetir a cada turno com uma ação.',
    '+1d6 por círculo acima do 3º.',
  ],
  [
    'Respirar na Água',
    'tra',
    '1 ação (ritual)',
    '9 metros',
    'V, S, M (um canudo)',
    '24 horas',
    'dr pt fe ma',
    "Até dez criaturas respiram debaixo d'água; elas perdem a respiração no ar.",
  ],
  [
    'Caminhar na Água',
    'tra',
    '1 ação (ritual)',
    '9 metros',
    'V, S, M (um pedaço de cortiça)',
    '1 hora',
    'cl dr pt fe',
    'Até dez criaturas andam sobre líquidos como se fossem sólidos.',
  ],
  [
    'Muralha de Vento',
    'evo',
    '1 ação',
    '36 metros',
    'V, S, M (um leque pequeno e uma pena exótica)',
    'Concentração, até 1 minuto',
    'dr pt',
    'Parede de vento de 15 metros de comprimento, 4,5 de altura e 30 cm de espessura que desvia projéteis e dispersa névoas e gases, deixando criaturas Pequenas ou menores com salvaguarda de Força.',
  ],
  [
    'Aura de Vitalidade',
    'evo',
    '1 ação',
    'Pessoal (raio de 9 metros)',
    'V',
    'Concentração, até 1 minuto',
    'pa',
    'Aura de cura: com uma ação bônus por turno você cura 2d6 PV de uma criatura nela.',
  ],
];
