import type { SpellRow } from './types';

export const C4: readonly SpellRow[] = [
  [
    'Olho Arcano',
    'adi',
    '1 ação',
    '9 metros',
    'V, S, M (um pouco de pelo de morcego)',
    'Concentração, até 1 hora',
    'ma',
    'Um olho invisível de 1,5 cm que você controla com a ação, voando 9 metros por turno e enxergando com visão no escuro de 9 metros.',
  ],
  [
    'Aura de Vida',
    'abj',
    '1 ação',
    'Pessoal (raio de 9 metros)',
    'V',
    'Concentração, até 10 minutos',
    'pa',
    'Criaturas em sua aura têm resistência a dano necrótico, e seu máximo de PV não pode ser reduzido. Aliados com 0 PV voltam com 1 PV.',
  ],
  [
    'Aura de Pureza',
    'abj',
    '1 ação',
    'Pessoal (raio de 9 metros)',
    'V',
    'Concentração, até 10 minutos',
    'pa',
    'Criaturas em sua aura têm resistência a dano de veneno e vantagem contra doença, condições e magias de encanto, entre outras.',
  ],
  [
    'Banimento',
    'abj',
    '1 ação',
    '18 metros',
    'V, S, M (um item do alvo repulsivo ao alvo)',
    'Concentração, até 1 minuto',
    'cl pa fe bx ma',
    'Uma criatura faz salvaguarda de Carisma ou é banida a um semiplano inofensivo (ou ao seu plano natal, se for de outro plano; nesse caso, se você mantiver a concentração por 1 minuto, ela não volta).',
    'Uma criatura adicional por círculo acima do 4º.',
  ],
  [
    'Praga',
    'nec',
    '1 ação',
    '9 metros',
    'V, S',
    'Instantânea',
    'dr bx fe ma',
    'Uma criatura faz salvaguarda de Constituição ou sofre 8d8 de dano necrótico (metade se passar). Plantas têm desvantagem; mortos-vivos e constructos são imunes.',
    '+1d8 por círculo acima do 4º.',
  ],
  [
    'Compulsão',
    'enc',
    '1 ação',
    '9 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'ba',
    'Criaturas à sua escolha fazem salvaguarda de Sabedoria ou se movem na direção que você indicar a cada turno, sem poder se mover de outra forma.',
  ],
  [
    'Confusão',
    'enc',
    '1 ação',
    '27 metros',
    'V, S, M (três cascas de noz)',
    'Concentração, até 1 minuto',
    'ba dr fe ma',
    'Criaturas em uma esfera de 3 metros de raio fazem salvaguarda de Sabedoria ou sofrem confusão: movem-se, atacam ou agem ao acaso conforme uma rolagem de d10.',
    '+1,5 metro de raio por círculo acima do 4º.',
  ],
  [
    'Conjurar Seres da Floresta',
    'con',
    '1 ação',
    '18 metros',
    'V, S, M (uma bolota ou um ramo de azevinho)',
    'Concentração, até 1 hora',
    'dr pt',
    'Convoca fadas obedientes: 1 de ND 2, 2 de ND 1, 4 de ND 1/2 ou 8 de ND 1/4.',
    'Mais fadas com círculos 6 e 8.',
  ],
  [
    'Conjurar Elementais Menores',
    'con',
    '1 minuto',
    '27 metros',
    'V, S',
    'Concentração, até 1 hora',
    'dr ma',
    'Convoca elementais obedientes: 1 de ND 2, 2 de ND 1, 4 de ND 1/2 ou 8 de ND 1/4.',
    'Mais elementais com círculos 6 e 8.',
  ],
  [
    'Controlar a Água',
    'tra',
    '1 ação',
    '90 metros',
    'V, S, M (uma gota de água e uma pitada de poeira)',
    'Concentração, até 10 minutos',
    'cl dr ma',
    'Controla um volume de água de até 30 metros de lado: inundar, partir, redirecionar, ou criar um redemoinho.',
  ],
  [
    'Proteção Contra a Morte',
    'abj',
    '1 ação',
    'Toque',
    'V, S',
    '8 horas',
    'cl pa',
    'A criatura tocada não morre uma vez: se for a 0 PV ou sofrer um efeito de morte instantânea, volta com 1 PV e a magia acaba.',
  ],
  [
    'Porta Dimensional',
    'con',
    '1 ação',
    '150 metros',
    'V',
    'Instantânea',
    'ba fe bx ma',
    'Você se teletransporta, com um objeto ou criatura voluntária que carregue, a um ponto que visualize ou descreva (distância e direção).',
  ],
  [
    'Adivinhação',
    'adi',
    '1 ação (ritual)',
    'Pessoal',
    'V, S, M (incenso e uma oferenda de 25 po, consumidos)',
    'Instantânea',
    'cl dr ma',
    'Você faz uma pergunta sobre algo que acontecerá nos próximos 7 dias e recebe uma resposta curta e precisa de uma divindade.',
  ],
  [
    'Dominar Fera',
    'enc',
    '1 ação',
    '18 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'dr fe',
    'Uma fera faz salvaguarda de Sabedoria ou fica sob seu controle telepático; ela tem vantagem se for ferida.',
    'Duração maior em círculos 5, 6 e 7+.',
  ],
  [
    'Tentáculos Negros de Evard',
    'con',
    '1 ação',
    '27 metros',
    'V, S, M (um pedaço de tentáculo de polvo ou lula)',
    'Concentração, até 1 minuto',
    'ma',
    'Tentáculos em um quadrado de 6 metros de lado: criaturas fazem salvaguarda de Destreza ou sofrem 3d6 de dano contundente e ficam impedidas, com mais dano a cada turno.',
  ],
  [
    'Fabricar',
    'tra',
    '10 minutos',
    '36 metros',
    'V, S',
    'Instantânea',
    'ma',
    'Converte matérias-primas em produtos acabados do mesmo material (uma ponte de madeira, uma corda), em até 1,5 metro cúbicos por 10 metros.',
  ],
  [
    'Escudo de Fogo',
    'evo',
    '1 ação',
    'Pessoal',
    'V, S, M (um pouco de fósforo)',
    '10 minutos',
    'fe ma',
    'Chamas envolvem você: resistência a frio ou fogo e 2d8 de dano de fogo ou gelo ao atacante corpo a corpo.',
  ],
  [
    'Liberdade de Movimento',
    'abj',
    '1 ação',
    'Toque',
    'V, S, M (uma tira de couro)',
    '1 hora',
    'ba cl dr pt',
    'A criatura tocada move-se sem penalidade de terreno difícil, magias ou imobilização, e escapa de agarramentos automaticamente.',
  ],
  [
    'Insetos Gigantes',
    'tra',
    '1 ação',
    '9 metros',
    'V, S',
    'Concentração, até 10 minutos',
    'dr',
    'Transforma até dez centopeias, três aranhas, cinco vespas ou um escorpião em versões gigantes que você comanda.',
  ],
  [
    'Videira Agarradora',
    'con',
    '1 ação bônus',
    '9 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'dr pt',
    'Uma videira surge do chão: ao agarrar uma criatura, a puxa até você (Força resiste) e a deixa agarrada.',
  ],
  [
    'Invisibilidade Maior',
    'ilu',
    '1 ação',
    'Toque',
    'V, S',
    'Concentração, até 1 minuto',
    'ba fe ma',
    'A criatura tocada fica invisível, sem que a magia termine ao atacar.',
  ],
  [
    'Guardião da Fé',
    'con',
    '1 ação',
    '9 metros',
    'V',
    '8 horas',
    'cl',
    'Um guardião espectral de 3 metros guarda um ponto; criaturas hostis que entrarem em 3 metros sofrem 20 de dano radiante (Destreza reduz à metade). Some após causar 60 de dano.',
  ],
  [
    'Terreno Alucinógeno',
    'ilu',
    '10 minutos',
    '90 metros',
    'V, S, M (uma pedra, um galho e uma folha verde)',
    '24 horas',
    'ba dr bx ma',
    'Faz um terreno natural em um cubo de 45 metros parecer outro. Estruturas não mudam.',
  ],
  [
    'Tempestade de Gelo',
    'evo',
    '1 ação',
    '90 metros',
    'V, S, M (uma pitada de poeira e algumas gotas de água)',
    'Instantânea',
    'dr fe ma',
    'Cilindro de 6 metros: 2d8 de dano contundente e 4d6 de dano de gelo (Destreza reduz à metade). O local vira terreno difícil.',
    '+1d8 de dano contundente por círculo acima do 4º.',
  ],
  [
    'Baú Secreto de Leomund',
    'con',
    '1 ação',
    'Toque',
    'V, S, M (um baú de 90 cm × 60 cm e sua réplica minúscula, no valor de 5.000 po)',
    'Instantânea',
    'ma',
    'Esconde um baú e seu conteúdo (até 12 pés cúbicos) no Plano Etéreo; você o convoca com a réplica.',
  ],
  [
    'Localizar Criatura',
    'adi',
    '1 ação',
    'Pessoal',
    'V, S, M (um pouco de pelo de cão de caça)',
    'Concentração, até 1 hora',
    'ba cl dr pa pt ma',
    'Você sente a direção de uma criatura que conhece ou descreve, a até 300 metros.',
  ],
  [
    'Cão Fiel de Mordenkainen',
    'con',
    '1 ação',
    '9 metros',
    'V, S, M (um minúsculo apito de prata, um osso e um fio)',
    '8 horas',
    'ma',
    'Um cão espectral que só você vê guarda uma área, late ao detectar invasores e morde (4d8 de dano perfurante).',
  ],
  [
    'Santuário Privado de Mordenkainen',
    'abj',
    '10 minutos',
    '36 metros',
    'V, S, M (uma folha de chumbo, uma peça opaca de vidro, algodão e pó de crisólita)',
    '24 horas',
    'ma',
    'Protege uma área de até 30 metros por lado contra bisbilhotagem, adivinhação e teletransporte, com opções adicionais.',
  ],
  [
    'Esfera Resiliente de Otiluke',
    'evo',
    '1 ação',
    '9 metros',
    'V, S, M (um hemisfério de cristal e de gomo)',
    'Concentração, até 1 minuto',
    'ma',
    'Uma esfera de força envolve uma criatura ou objeto: nada atravessa. A criatura dentro fica impedida de se mover por conta própria, mas pode ser rolada.',
  ],
  [
    'Assassino Fantasmagórico',
    'ilu',
    '1 ação',
    '36 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'ba ma',
    'A criatura faz salvaguarda de Sabedoria ou vê seu pior medo e sofre 4d10 de dano psíquico por turno, repetindo a salvaguarda ao fim de cada turno.',
    '+1d10 por círculo acima do 4º.',
  ],
  [
    'Polimorfia',
    'tra',
    '1 ação',
    '18 metros',
    'V, S, M (um casulo de lagarta)',
    'Concentração, até 1 hora',
    'ba dr fe ma',
    'Transforma uma criatura em fera de ND igual ou menor que o nível ou ND dela (Sabedoria resiste). Os PV da fera substituem os dela.',
  ],
  [
    'Golpe Atordoante',
    'evo',
    '1 ação bônus',
    'Pessoal',
    'V',
    'Concentração, até 1 minuto',
    'pa',
    'No próximo acerto com arma corpo a corpo, 4d6 de dano psíquico extra e o alvo faz salvaguarda de Sabedoria ou tem desvantagem em ataques e testes de atributo e não pode usar reações até o fim do seu próximo turno.',
  ],
  [
    'Moldar Pedra',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (barro mole)',
    'Instantânea',
    'cl dr ma',
    'Remodela um pedaço de pedra de até 1,5 metro cúbico para outra forma útil: porta, passagem, tampa.',
  ],
  [
    'Pele de Pedra',
    'abj',
    '1 ação',
    'Toque',
    'V, S, M (pó de diamante no valor de 100 po, consumido)',
    'Concentração, até 1 hora',
    'dr pt fe ma',
    'A criatura tocada ganha resistência a dano contundente, cortante e perfurante não mágico.',
  ],
  [
    'Muralha de Fogo',
    'evo',
    '1 ação',
    '36 metros',
    'V, S, M (um pedaço de fósforo)',
    'Concentração, até 1 minuto',
    'dr fe ma',
    'Parede de chamas de até 18 metros de comprimento: 5d8 de dano de fogo em um lado (Destreza reduz à metade). Pode formar um anel.',
    '+1d8 por círculo acima do 4º.',
  ],
];
