import type { SpellRow } from './types';

export const C5: readonly SpellRow[] = [
  [
    'Animar Objetos',
    'tra',
    '1 ação',
    '36 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'ba fe ma',
    'Até dez objetos ganham vida e atacam sob seu comando (a ação bônus os comanda), com PV, CA e dano conforme o tamanho.',
    'Mais objetos por círculo acima do 5º.',
  ],
  [
    'Concha Antivida',
    'abj',
    '1 ação',
    'Pessoal (raio de 3 metros)',
    'V, S',
    'Concentração, até 1 hora',
    'dr',
    'Barreira que impede criaturas vivas (exceto constructos e mortos-vivos) de passarem.',
  ],
  [
    'Despertar',
    'tra',
    '8 horas',
    'Toque',
    'V, S, M (uma ágata de 1.000 po, consumida)',
    'Instantânea',
    'ba dr',
    'Concede Inteligência 10 e a capacidade de entender e falar idiomas a uma fera ou planta com 0 de Inteligência, tornando-a sua amiga por 30 dias.',
  ],
  [
    'Golpe Banidor',
    'abj',
    '1 ação bônus',
    'Pessoal',
    'V',
    'Concentração, até 1 minuto',
    'pa',
    'No próximo acerto com arma, 5d10 de dano de força extra; se a criatura ficar com 50 PV ou menos, é banida a um semiplano.',
  ],
  [
    'Mão de Bigby',
    'evo',
    '1 ação',
    '36 metros',
    'V, S, M (uma casca de ovo e uma luva de couro)',
    'Concentração, até 1 minuto',
    'ma',
    'Uma mão Grande de força que você controla: golpeia (4d8), empurra, agarra ou serve de escudo (cobertura de três quartos).',
    '+2d8 no golpe ou +2d6 no aperto por círculo acima do 5º.',
  ],
  [
    'Círculo de Poder',
    'abj',
    '1 ação',
    'Pessoal (raio de 9 metros)',
    'V',
    'Concentração, até 10 minutos',
    'pa',
    'Aura de 9 metros: você e aliados têm vantagem em salvaguardas contra magias e efeitos mágicos, e metade do dano de salvaguardas bem-sucedidas vira zero.',
  ],
  [
    'Nuvem Mortal',
    'con',
    '1 ação',
    '36 metros',
    'V, S',
    'Concentração, até 10 minutos',
    'fe ma',
    'Esfera de 6 metros de névoa venenosa que se move 3 metros por turno: 5d8 de dano de veneno (Constituição reduz à metade) a cada turno.',
    '+1d8 por círculo acima do 5º.',
  ],
  [
    'Comunhão',
    'adi',
    '1 minuto (ritual)',
    'Pessoal',
    'V, S, M (incenso e um frasco de água benta ou impura)',
    '1 minuto',
    'cl',
    'Você contata sua divindade e faz até três perguntas que podem ser respondidas com sim ou não.',
  ],
  [
    'Comunhão com a Natureza',
    'adi',
    '1 minuto (ritual)',
    'Pessoal',
    'V, S',
    'Instantânea',
    'dr pt',
    'Você ganha conhecimento da região num raio de 4,5 km (ou 450 m em ambientes subterrâneos): terreno, plantas, minerais, criaturas, água e povoados.',
  ],
  [
    'Cone de Frio',
    'evo',
    '1 ação',
    'Pessoal (cone de 18 metros)',
    'V, S, M (um pequeno cone de cristal ou vidro)',
    'Instantânea',
    'fe ma',
    'Explosão de frio: 8d8 de dano de gelo (Constituição reduz à metade). Criaturas mortas viram estátuas de gelo.',
    '+1d8 por círculo acima do 5º.',
  ],
  [
    'Conjurar Elemental',
    'con',
    '1 minuto',
    '27 metros',
    'V, S, M (incenso para o ar, argila para a terra, enxofre e fósforo para o fogo, ou água e areia para a água)',
    'Concentração, até 1 hora',
    'dr ma',
    'Convoca um elemental de ND 5 ou menor no espaço que você escolher. Se perder a concentração, ele se torna hostil.',
    'ND +1 por círculo acima do 5º.',
  ],
  [
    'Conjurar Rajada',
    'con',
    '1 ação',
    '45 metros',
    'V, S, M (uma munição ou uma arma de arremesso)',
    'Instantânea',
    'pt',
    'Uma rajada de projéteis cai sobre um cilindro de 12 metros de raio e 6 de altura: 8d8 de dano (Destreza reduz à metade).',
  ],
  [
    'Contatar Outro Plano',
    'adi',
    '1 minuto (ritual)',
    'Pessoal',
    'V',
    '1 minuto',
    'bx ma',
    'Você consulta uma entidade de outro plano (salvaguarda de Inteligência, CD 15); pode ficar insano. Faz cinco perguntas curtas.',
  ],
  [
    'Contágio',
    'nec',
    '1 ação',
    'Toque',
    'V, S',
    '7 dias',
    'cl dr',
    'Ataque de magia corpo a corpo: a criatura contrai uma doença à sua escolha (Cegueira, Febre, Mal da Sarna etc.). Após falhas repetidas, a doença se instala.',
  ],
  [
    'Criação',
    'ilu',
    '1 minuto',
    '9 metros',
    'V, S, M (um pincel pequeno)',
    'Especial',
    'fe ma',
    'Cria um objeto inanimado de matéria vegetal ou mineral de 1,5 m³ de volume. A duração depende do material.',
    '+1,5 m³ por círculo acima do 5º.',
  ],
  [
    'Onda Destrutiva',
    'evo',
    '1 ação',
    'Pessoal (esfera de 9 metros)',
    'V',
    'Instantânea',
    'pa',
    'Criaturas que escolher fazem salvaguarda de Constituição: 5d6 de dano trovejante e 5d6 radiante ou necrótico, e ficam caídas.',
  ],
  [
    'Dissipar o Bem e o Mal',
    'abj',
    '1 ação',
    'Pessoal',
    'V, S, M (água benta ou pó de prata e ferro)',
    'Concentração, até 1 minuto',
    'cl pa',
    'Escudo de energia: celestiais, elementais, fadas, corruptores e mortos-vivos têm desvantagem contra você. Você pode encerrar encanto e outros efeitos.',
  ],
  [
    'Dominar Pessoa',
    'enc',
    '1 ação',
    '18 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'ba fe ma',
    'Um humanoide faz salvaguarda de Sabedoria ou fica sob seu controle; vantagem na salvaguarda se você o estiver ferindo.',
    'Duração maior em círculos 6, 7 e 8+.',
  ],
  [
    'Sonho',
    'ilu',
    '1 minuto',
    'Especial',
    'V, S, M (um punhado de areia, tinta e uma pena de ave que dormiu)',
    '8 horas',
    'ba bx ma',
    'Você ou criatura voluntária tocada entra no sonho de outra criatura e conversa com ela, ou a atormenta com pesadelos.',
  ],
  [
    'Coluna de Chamas',
    'evo',
    '1 ação',
    '18 metros',
    'V, S, M (uma pitada de enxofre)',
    'Instantânea',
    'cl',
    'Coluna de fogo divino de 3 metros de raio: 4d6 de dano de fogo e 4d6 radiante (Destreza reduz à metade).',
    '+1d6 de dano de fogo ou radiante por círculo acima do 5º.',
  ],
  [
    'Missão',
    'enc',
    '1 minuto',
    '18 metros',
    'V',
    '30 dias',
    'ba cl dr pa ma',
    'Você impõe uma ordem a uma criatura (Sabedoria resiste). Descumpri-la causa 5d10 de dano psíquico por dia.',
    'Duração maior em círculos 7 e 9.',
  ],
  [
    'Restauração Maior',
    'abj',
    '1 ação',
    'Toque',
    'V, S, M (pó de diamante no valor de 100 po, consumido)',
    'Instantânea',
    'ba cl dr',
    'Remove um efeito de uma lista: encanto, petrificação, maldição, redução de atributo ou PV, ou exaustão.',
  ],
  [
    'Consagrar',
    'evo',
    '24 horas',
    'Toque',
    'V, S, M (ervas, óleos e incenso no valor de 1.000 po, consumidos)',
    'Até ser dissipada',
    'cl',
    'Santifica uma área de 18 metros de raio: ela protege contra aberrações, corruptores e outros, e permite escolher efeitos extras (medo, coragem, língua etc.).',
  ],
  [
    'Imobilizar Monstro',
    'enc',
    '1 ação',
    '27 metros',
    'V, S, M (um pequeno pedaço de ferro reto)',
    'Concentração, até 1 minuto',
    'ba fe bx ma',
    'Uma criatura faz salvaguarda de Sabedoria ou fica paralisada, repetindo ao fim de cada turno.',
    'Uma criatura adicional por círculo acima do 5º.',
  ],
  [
    'Praga de Insetos',
    'con',
    '1 ação',
    '90 metros',
    'V, S, M (alguns grãos de açúcar, fósforos e uma gota de gordura)',
    'Concentração, até 10 minutos',
    'cl dr fe',
    'Nuvem de 6 metros de raio de insetos que obstruem a visão e causam 4d10 de dano perfurante (Constituição reduz à metade).',
    '+1d10 por círculo acima do 5º.',
  ],
  [
    'Conhecimento Lendário',
    'adi',
    '10 minutos',
    'Pessoal',
    'V, S, M (incenso e quatro tiras de marfim, 250 po cada)',
    'Instantânea',
    'ba cl ma',
    'Você obtém informações sobre um objeto, lugar ou pessoa famosa que nomeie, em quantidade conforme o seu conhecimento prévio.',
  ],
  [
    'Curar Ferimentos em Massa',
    'evo',
    '1 ação',
    '18 metros',
    'V, S',
    'Instantânea',
    'ba cl dr',
    'Até seis criaturas recuperam 3d8 + modificador de conjuração em PV.',
    '+1d8 por círculo acima do 5º.',
  ],
  [
    'Mistificação',
    'ilu',
    '1 ação',
    'Pessoal',
    'S',
    'Concentração, até 1 hora',
    'ba bx ma',
    'Você fica invisível e cria um duplo ilusório de si mesmo no local de sua escolha, que age como você enquanto a magia durar.',
  ],
  [
    'Modificar Memória',
    'enc',
    '1 ação',
    '9 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'ba ma',
    'Uma criatura faz salvaguarda de Sabedoria ou tem a memória de um evento recente alterada ou apagada por você.',
    'Mais tempo no passado com círculos acima do 5º.',
  ],
  [
    'Passagem',
    'tra',
    '1 ação',
    '9 metros',
    'V, S, M (um punhado de sementes de gergelim)',
    '1 hora',
    'ma',
    'Cria uma passagem de 1,5 × 2,5 × 6 metros em madeira, gesso ou pedra.',
  ],
  [
    'Elo Planar',
    'abj',
    '1 hora',
    '18 metros',
    'V, S, M (uma joia no valor de 1.000 po, consumida)',
    '24 horas',
    'ba cl dr ma',
    'Prende um elemental, celestial, corruptor ou fada a seu serviço, sob um acordo, depois de um teste de Carisma.',
    'Duração maior em círculos 6, 7 e 8+.',
  ],
  [
    'Reviver Mortos',
    'nec',
    '1 hora',
    'Toque',
    'V, S, M (um diamante de 500 po, consumido)',
    'Instantânea',
    'ba cl pa',
    'Traz de volta uma criatura morta há até 10 dias com 1 PV e −4 em todas as jogadas, que melhora a cada descanso longo.',
  ],
  [
    'Vínculo Telepático de Rary',
    'adi',
    '1 ação (ritual)',
    '9 metros',
    'V, S, M (peças de casca de ovo de dois tipos diferentes de criaturas)',
    '1 hora',
    'ba ma',
    'Cria um elo telepático entre até oito criaturas, que se comunicam a qualquer distância no mesmo plano.',
  ],
  [
    'Reencarnar',
    'tra',
    '1 hora',
    'Toque',
    'V, S, M (óleos raros e unguentos no valor de 1.000 po, consumidos)',
    'Instantânea',
    'dr',
    'Traz de volta uma criatura morta há até 10 dias em um novo corpo de uma raça determinada por rolagem de d100.',
  ],
  [
    'Vidência',
    'adi',
    '10 minutos',
    'Pessoal',
    'V, S, M (um foco no valor de 1.000 po, como cristal ou uma bacia de prata)',
    'Concentração, até 10 minutos',
    'ba cl dr bx ma',
    'Você enxerga e ouve uma criatura à distância por meio de um sensor invisível, com bônus de conhecimento sobre ela (salvaguarda de Sabedoria).',
  ],
  [
    'Aparência',
    'ilu',
    '1 ação',
    '9 metros',
    'V, S',
    '8 horas',
    'ba fe ma',
    'Muda a aparência de até oito criaturas, incluindo roupas e equipamento, enquanto elas permanecerem voluntárias.',
  ],
  [
    'Aljava Veloz',
    'tra',
    '1 ação bônus',
    'Toque',
    'V, S, M (uma aljava no valor de 1.000 po, consumida)',
    'Concentração, até 1 minuto',
    'pt',
    'Uma aljava vira fonte de projéteis mágicos; com ação bônus você dispara dois disparos de arma por turno.',
  ],
  [
    'Telecinese',
    'tra',
    '1 ação',
    '18 metros',
    'V, S',
    'Concentração, até 10 minutos',
    'fe ma',
    'Você move uma criatura Enorme ou menor, ou um objeto de até 500 kg, a até 9 metros. Criaturas fazem salvaguarda de Força.',
  ],
  [
    'Círculo de Teletransporte',
    'con',
    '1 minuto',
    '3 metros',
    'V, M (giz e tinta de ervas raras no valor de 50 po, consumidos)',
    '1 rodada',
    'ba fe ma',
    'Cria um círculo de 3 metros de diâmetro que leva a outro círculo permanente que você conheça no mesmo plano.',
  ],
  [
    'Caminhar por Árvores',
    'con',
    '1 ação',
    'Pessoal',
    'V, S',
    'Concentração, até 1 minuto',
    'dr pt',
    'Você entra numa árvore e sai de outra do mesmo tipo a até 150 metros, usando 1,5 metro de movimento por vez.',
  ],
  [
    'Muralha de Força',
    'evo',
    '1 ação',
    '36 metros',
    'V, S, M (um pedaço de pó de gema transparente)',
    'Concentração, até 10 minutos',
    'ma',
    'Cria uma parede invisível de força, indestrutível por dano e imune a dissipação. Pode ser um domo ou parede plana de 10 painéis de 3 metros.',
  ],
  [
    'Muralha de Pedra',
    'evo',
    '1 ação',
    '36 metros',
    'V, S, M (um bloco pequeno de granito)',
    'Concentração, até 10 minutos',
    'cl dr fe ma',
    'Parede de pedra de até 10 painéis de 3 metros, com 15 cm de espessura, que se torna permanente se concentrar por toda a duração.',
  ],
];
