import type { SpellRow } from './types';

export const C6: readonly SpellRow[] = [
  [
    'Portal Arcano',
    'con',
    '1 ação',
    '150 metros',
    'V, S, M (cristal ou vidro no valor de 100 po)',
    'Concentração, até 10 minutos',
    'bx fe ma',
    'Cria dois portais ligados em pontos que você vê, a até 150 metros de distância um do outro; criaturas atravessam de um para o outro.',
  ],
  [
    'Barreira de Lâminas',
    'evo',
    '1 ação',
    '27 metros',
    'V, S',
    'Concentração, até 10 minutos',
    'cl',
    'Muralha de lâminas giratórias de 30 metros: 6d10 de dano cortante (Destreza reduz à metade) a quem entrar ou começar o turno ali; é cobertura de três quartos.',
  ],
  [
    'Relâmpago em Cadeia',
    'evo',
    '1 ação',
    '45 metros',
    'V, S, M (um pouco de pelo, âmbar, vidro e três pinos de prata)',
    'Instantânea',
    'fe ma',
    'Um raio atinge o alvo (10d8 de dano elétrico) e salta para até três criaturas a 9 metros do alvo; Destreza reduz à metade.',
    '+1 criatura adicional por círculo acima do 6º.',
  ],
  [
    'Círculo da Morte',
    'nec',
    '1 ação',
    '45 metros',
    'V, S, M (o pó de uma pérola negra no valor de 500 po)',
    'Instantânea',
    'fe bx ma',
    'Esfera de 18 metros de raio: 8d6 de dano necrótico (Constituição reduz à metade).',
    '+2d6 por círculo acima do 6º.',
  ],
  [
    'Conjurar Fada',
    'con',
    '1 minuto',
    '27 metros',
    'V, S',
    'Concentração, até 1 hora',
    'dr bx',
    'Convoca uma fada de ND 6 ou menos. Se perder a concentração, ela se torna hostil.',
    'ND +1 por círculo acima do 6º.',
  ],
  [
    'Contingência',
    'evo',
    '10 minutos',
    'Pessoal',
    'V, S, M (uma estatueta sua, cravejada de gemas no valor de 1.500 po)',
    '10 dias',
    'ma',
    'Você prepara uma magia de até 5º círculo que dispara sozinha quando uma condição que você definiu ocorrer.',
  ],
  [
    'Criar Mortos-Vivos',
    'nec',
    '1 minuto',
    '3 metros',
    'V, S, M (um pote de argila, terra de sepultura e uma pedra negra de 150 po para cada cadáver)',
    'Instantânea',
    'cl bx ma',
    'Transforma até três corpos em carniçais ou outros mortos-vivos obedientes à noite.',
    'Mais ou mais fortes mortos-vivos em círculos 7, 8 e 9.',
  ],
  [
    'Desintegrar',
    'tra',
    '1 ação',
    '18 metros',
    'V, S, M (uma pedra-ímã e uma pitada de poeira)',
    'Instantânea',
    'fe ma',
    'Raio verde: 10d6 + 40 de dano de força (Destreza evita). Se o alvo ficar com 0 PV, vira um monte de pó.',
    '+3d6 por círculo acima do 6º.',
  ],
  [
    'Invocação Instantânea de Drawmij',
    'con',
    '1 minuto (ritual)',
    'Toque',
    'V, S, M (uma safira de 1.000 po)',
    'Até ser dissipada',
    'ma',
    'Você marca um objeto de até 4,5 kg com a safira; mais tarde, o convoca à sua mão, de qualquer distância.',
  ],
  [
    'Mau-olhado',
    'nec',
    '1 ação',
    'Pessoal',
    'V, S',
    'Concentração, até 1 minuto',
    'ba bx fe ma',
    'A cada turno, com uma ação, você aplica um efeito a uma criatura que veja: adormecer, amedrontar ou causar enjoo.',
  ],
  [
    'Encontrar o Caminho',
    'adi',
    '1 minuto',
    'Pessoal',
    'V, S, M (um conjunto de ferramentas de adivinhação e um objeto do local)',
    'Concentração, até 1 dia',
    'ba cl dr',
    'Você sabe a rota mais curta e direta até um local fixo que conheça, no mesmo plano.',
  ],
  [
    'Carne para Pedra',
    'tra',
    '1 ação',
    '18 metros',
    'V, S, M (uma pitada de cal, água e terra)',
    'Concentração, até 1 minuto',
    'bx fe ma',
    'Uma criatura faz salvaguardas de Constituição; falhas sucessivas a deixam impedida e depois petrificada.',
  ],
  [
    'Interdição',
    'abj',
    '1 minuto (ritual)',
    'Toque',
    'V, S, M (um borrifo de água benta, incenso e pó de rubi de 1.000 po)',
    '1 dia',
    'cl',
    'Protege uma área de até 3.700 m² contra teletransporte, viagem planar e criaturas de tipos escolhidos, que sofrem 5d10 de dano radiante ou necrótico.',
  ],
  [
    'Globo de Invulnerabilidade',
    'abj',
    '1 ação',
    'Pessoal (raio de 3 metros)',
    'V, S, M (uma conta de vidro)',
    'Concentração, até 1 minuto',
    'fe ma',
    'Esfera que bloqueia magias de 5º círculo ou menor lançadas de fora para dentro.',
    'Bloqueia mais um círculo por círculo acima do 6º.',
  ],
  [
    'Guardas e Proteções',
    'abj',
    '10 minutos',
    'Toque',
    'V, S, M (incenso queimado, fita de enxofre, óleo e uma varinha de prata no valor de 10 po)',
    '24 horas',
    'ba ma',
    'Protege uma área de até 750 m² com neblina, portas trancadas, teias, ilusões e sugestão, entre outras defesas.',
  ],
  [
    'Ferir',
    'nec',
    '1 ação',
    '18 metros',
    'V, S',
    'Instantânea',
    'cl',
    'Criatura faz salvaguarda de Constituição ou sofre 14d6 de dano necrótico (metade se passar); seus PV não podem cair abaixo de 1.',
  ],
  [
    'Cura',
    'evo',
    '1 ação',
    '18 metros',
    'V, S',
    'Instantânea',
    'cl dr',
    'Restaura 70 PV de uma criatura e remove cegueira, surdez e doenças.',
    '+10 PV por círculo acima do 6º.',
  ],
  [
    'Banquete dos Heróis',
    'con',
    '10 minutos',
    '9 metros',
    'V, S, M (uma tigela de gemas no valor de 1.000 po, consumida)',
    'Instantânea',
    'ba cl dr',
    'Banquete para até doze criaturas: elas ficam imunes a veneno e medo, ganham vantagem em Sabedoria e +2d10 PV máximos por 24 horas.',
  ],
  [
    'Frasco Mágico',
    'nec',
    '1 minuto',
    'Pessoal',
    'V, S, M (uma gema, cristal, relicário ou receptáculo no valor de 500 po)',
    'Até ser dissipada',
    'ma',
    'Sua alma entra em um recipiente e pode possuir um corpo próximo (Carisma resiste).',
  ],
  [
    'Sugestão em Massa',
    'enc',
    '1 ação',
    '18 metros',
    'V, M (uma língua de cobra e um favo de mel)',
    '24 horas',
    'ba bx fe ma',
    'Até doze criaturas fazem salvaguarda de Sabedoria ou obedecem a uma sugestão sua.',
    'Duração maior em círculos 7, 8 e 9.',
  ],
  [
    'Mover Terra',
    'tra',
    '1 ação',
    '36 metros',
    'V, S, M (uma lâmina de ferro e um saquinho de terra)',
    'Concentração, até 2 horas',
    'dr fe ma',
    'Remodela o solo de uma área de 12 metros de lado: eleva, rebaixa, move terra, areia e argila.',
  ],
  [
    'Esfera Congelante de Otiluke',
    'evo',
    '1 ação',
    '90 metros',
    'V, S, M (uma pequena esfera de cristal)',
    'Instantânea',
    'ma',
    'Esfera de gelo de 18 metros de raio explode: 10d6 de dano de gelo (Constituição reduz à metade). A água atingida congela.',
    '+1d6 por círculo acima do 6º.',
  ],
  [
    'Dança Irresistível de Otto',
    'enc',
    '1 ação',
    '9 metros',
    'V',
    'Concentração, até 1 minuto',
    'ba ma',
    'Uma criatura dança sem controle, com deslocamento 0, desvantagem em ataques e salvaguardas de Destreza, e ataques contra ela com vantagem.',
  ],
  [
    'Aliado Planar',
    'con',
    '10 minutos',
    '18 metros',
    'V, S',
    'Instantânea',
    'cl',
    'Você pede ajuda a uma entidade extraplanar, que envia um servo em troca de pagamento.',
  ],
  [
    'Ilusão Programada',
    'ilu',
    '1 ação',
    '36 metros',
    'V, S, M (um pouco de lã e pó de jade no valor de 25 po)',
    'Até ser dissipada',
    'ba ma',
    'Uma ilusão em um cubo de 9 metros é disparada por um gatilho que você definiu e age conforme o que você programou.',
  ],
  [
    'Raio de Sol',
    'evo',
    '1 ação',
    'Pessoal (linha de 18 metros)',
    'V, S, M (uma lupa)',
    'Concentração, até 1 minuto',
    'dr fe ma',
    'Raio de luz de 18 metros: 6d8 de dano radiante (Constituição reduz à metade) e cegueira. Pode repetir a cada turno.',
  ],
  [
    'Transporte via Plantas',
    'con',
    '1 ação',
    '3 metros',
    'V, S',
    '1 rodada',
    'dr',
    'Liga duas plantas grandes no mesmo plano; criaturas viajam entre elas instantaneamente.',
  ],
  [
    'Visão da Verdade',
    'adi',
    '1 ação',
    'Toque',
    'V, S, M (um unguento de cogumelo, no valor de 25 po, consumido)',
    '1 hora',
    'ba cl fe bx ma',
    'A criatura tocada enxerga no escuro, vê invisíveis, enxerga ilusões e transformações, e vê o Plano Etéreo, até 36 metros.',
  ],
  [
    'Muralha de Gelo',
    'evo',
    '1 ação',
    '36 metros',
    'V, S, M (um pequeno pedaço de quartzo)',
    'Concentração, até 10 minutos',
    'ma',
    'Parede de gelo de até 10 painéis; cada painel tem 30 PV. Se destruído, deixa ar frio que causa 5d6 de dano de gelo.',
    '+2d6 por círculo acima do 6º.',
  ],
  [
    'Muralha de Espinhos',
    'con',
    '1 ação',
    '36 metros',
    'V, S, M (um punhado de espinhos)',
    'Concentração, até 10 minutos',
    'dr',
    'Parede de arbustos espinhosos de 18 metros de comprimento: 7d8 de dano perfurante a quem tocar ou entrar nela; terreno difícil.',
    '+1d8 por círculo acima do 6º.',
  ],
  [
    'Caminhar no Vento',
    'tra',
    '1 minuto',
    '9 metros',
    'V, S, M (fogo e água benta)',
    '8 horas',
    'dr',
    'Você e até dez criaturas viram nuvens e viajam pelo ar a 90 metros por turno.',
  ],
  [
    'Palavra de Recordação',
    'con',
    '1 ação',
    '1,5 metro',
    'V',
    'Instantânea',
    'cl',
    'Você e até cinco criaturas voluntárias a 1,5 metro se teletransportam para um santuário seguro previamente designado.',
  ],
];
