import type { SpellRow } from './types';

export const C7: readonly SpellRow[] = [
  [
    'Conjurar Celestial',
    'con',
    '1 minuto',
    '27 metros',
    'V, S',
    'Concentração, até 1 hora',
    'cl',
    'Convoca um celestial de ND 4 ou menos que luta por você ou segue ordens.',
    'ND maior com círculo 9.',
  ],
  [
    'Bola de Fogo Controlada',
    'evo',
    '1 ação',
    '45 metros',
    'V, S, M (uma bolinha de guano de morcego e enxofre)',
    'Concentração, até 1 minuto',
    'fe ma',
    'Uma conta brilhante explode quando a concentração termina ou é detonada: 12d6 de dano de fogo (Destreza reduz à metade) que sobe 1d6 por rodada de espera.',
    '+1d6 por círculo acima do 7º.',
  ],
  [
    'Palavra Divina',
    'evo',
    '1 ação bônus',
    '9 metros',
    'V',
    'Instantânea',
    'cl',
    'Criaturas que você escolher que ouvem a palavra sofrem efeitos conforme os PV atuais: surdez, cegueira, atordoamento ou morte.',
  ],
  [
    'Forma Etérea',
    'tra',
    '1 ação',
    'Pessoal',
    'V, S',
    'Até 8 horas',
    'ba bx cl fe ma',
    'Você entra no Plano Etéreo, onde se move em todas as direções e interage com o plano material parcialmente.',
    'Mais criaturas com círculo 8 ou maior.',
  ],
  [
    'Dedo da Morte',
    'nec',
    '1 ação',
    '18 metros',
    'V, S',
    'Instantânea',
    'bx fe ma',
    'Criatura faz salvaguarda de Constituição ou sofre 7d8 + 30 de dano necrótico (metade se passar). Quem morrer assim vira um zumbi seu.',
  ],
  [
    'Tempestade de Fogo',
    'evo',
    '1 ação',
    '45 metros',
    'V, S',
    'Instantânea',
    'cl dr fe',
    'Chamas em até dez cubos de 3 metros: 7d10 de dano de fogo (Destreza reduz à metade). Incendeia objetos inflamáveis.',
  ],
  [
    'Jaula de Força',
    'evo',
    '1 ação',
    '30 metros',
    'V, S, M (pó de rubi no valor de 1.500 po)',
    '1 hora',
    'ba bx ma',
    'Uma jaula invisível de 6 metros ou uma caixa de 3 metros prende criaturas; nada atravessa; só Teletransporte (com salvaguarda de Carisma) permite sair.',
  ],
  [
    'Miragem',
    'ilu',
    '10 minutos',
    'Visão',
    'V, S',
    '10 dias',
    'ba dr ma',
    'Faz um terreno de até 1,5 km de lado parecer e soar outro, inclusive estruturas, que você pode ocultar, criar ou alterar.',
  ],
  [
    'Mansão Magnífica de Mordenkainen',
    'con',
    '1 minuto',
    '90 metros',
    'V, S, M (um minúsculo portal de marfim, uma miniatura de mármore e uma colher de prata, 5 po)',
    '24 horas',
    'ba ma',
    'Cria uma entrada para um espaço extradimensional luxuoso com servos invisíveis e banquete para até cem convidados.',
  ],
  [
    'Espada de Mordenkainen',
    'evo',
    '1 ação',
    '18 metros',
    'V, S, M (uma espada de platina em miniatura, 250 po)',
    'Concentração, até 1 minuto',
    'ba ma',
    'Uma espada de força ataca por você: 3d10 de dano de força (ataque de magia corpo a corpo); ação bônus para mover e atacar.',
  ],
  [
    'Mudança de Plano',
    'con',
    '1 ação',
    'Toque',
    'V, S, M (uma forquilha de metal sintonizada ao plano, no valor de 250 po)',
    'Instantânea',
    'cl dr bx fe ma',
    'Você e até oito criaturas voluntárias (de mãos dadas) viajam a outro plano; ou, com ataque corpo a corpo, bane uma criatura (Carisma resiste).',
  ],
  [
    'Spray Prismático',
    'evo',
    '1 ação',
    'Pessoal (cone de 18 metros)',
    'V, S',
    'Instantânea',
    'ba fe ma',
    'Oito raios coloridos (1d8 decide cada um): efeitos de dano de 10d6 e condições como restringido, cego, desintegrado, petrificado.',
  ],
  [
    'Projetar Imagem',
    'ilu',
    '1 ação',
    '750 quilômetros',
    'V, S, M (uma réplica sua pequena, no valor de 5 po)',
    'Concentração, até 1 dia',
    'ba ma',
    'Projeta uma cópia ilusória de você num local que já visitou, que fala, age e conjura através de você.',
  ],
  [
    'Regeneração',
    'tra',
    '1 minuto',
    'Toque',
    'V, S, M (uma roda de oração e água benta)',
    '1 hora',
    'ba cl dr',
    'A criatura tocada recupera 4d8 + 15 PV e mais 1 PV por turno; membros cortados voltam a crescer após 2 minutos.',
  ],
  [
    'Ressurreição',
    'nec',
    '1 hora',
    'Toque',
    'V, S, M (um diamante de 1.000 po, consumido)',
    'Instantânea',
    'ba cl',
    'Traz de volta uma criatura morta há até 100 anos com PV máximos, restaurando partes do corpo, com −4 em jogadas que diminui a cada descanso longo.',
  ],
  [
    'Inverter a Gravidade',
    'tra',
    '1 ação',
    '30 metros',
    'V, S, M (uma pedra-ímã e limalha de ferro)',
    'Concentração, até 1 minuto',
    'dr fe ma',
    'Inverte a gravidade em cilindro de 15 metros de raio e 30 de altura; criaturas e objetos caem para cima.',
  ],
  [
    'Sequestrar',
    'tra',
    '1 ação',
    'Toque',
    'V, S, M (pó de diamante, esmeralda, rubi e safira no valor de 5.000 po)',
    'Até ser dissipada',
    'ma',
    'Esconde uma criatura voluntária ou objeto de toda adivinhação, deixando-os em estado de animação suspensa.',
  ],
  [
    'Simulacro',
    'ilu',
    '12 horas',
    'Toque',
    'V, S, M (neve ou gelo suficiente para uma réplica, pó de rubi no valor de 1.500 po)',
    'Até ser dissipada',
    'ma',
    'Cria um duplo de uma besta ou humanoide, com metade dos PV, que obedece a você.',
  ],
  [
    'Símbolo',
    'abj',
    '1 minuto',
    'Toque',
    'V, S, M (mercúrio, fósforo e pó de diamante e opala, no total de 1.000 po)',
    'Até ser dissipada ou ativada',
    'ba cl dr ma',
    'Grava uma runa que dispara quando tocada ou vista; efeitos: morte, discórdia, medo, dor, sono, atordoamento ou desesperança.',
  ],
  [
    'Teletransporte',
    'con',
    '1 ação',
    '3 metros',
    'V',
    'Instantânea',
    'ba fe ma',
    'Teleporta você e até oito criaturas a um destino de sua escolha; o risco depende de quão bem você conhece o local.',
  ],
];
