import type { SpellRow } from './types';

export const C8: readonly SpellRow[] = [
  [
    'Formas Animais',
    'tra',
    '1 ação',
    '18 metros',
    'V, S',
    'Concentração, até 24 horas',
    'dr',
    'Transforma criaturas voluntárias à sua escolha em feras de ND 4 ou menos, que mantêm o próprio PV e se transformam novamente ao fim.',
  ],
  [
    'Campo Antimagia',
    'abj',
    '1 ação',
    'Pessoal (esfera de 3 metros)',
    'V, S, M (pó de ferro ou limalha de ferro)',
    'Concentração, até 1 hora',
    'cl ma',
    'Esfera ao seu redor onde magias e efeitos mágicos não funcionam e itens mágicos se tornam comuns.',
  ],
  [
    'Antipatia/Simpatia',
    'enc',
    '1 hora',
    '18 metros',
    'V, S, M (alúmen mergulhado em vinagre e uma pitada de mel ou ouro)',
    '10 dias',
    'ba dr ma',
    'Atrai ou repele um tipo de criatura (Sabedoria resiste), criando uma compulsão a aproximar-se ou a fugir de um objeto ou área.',
  ],
  [
    'Clone',
    'nec',
    '1 hora',
    'Toque',
    'V, S, M (um diamante de 1.000 po e um frasco de 2.000 po, e um pedaço de carne do alvo)',
    'Instantânea',
    'ma',
    'Cria um clone inerte de uma criatura; se ela morrer, sua alma se transfere ao clone em 120 dias.',
  ],
  [
    'Controlar o Clima',
    'tra',
    '10 minutos',
    'Pessoal (8 km)',
    'V, S, M (incenso queimado e pedaços de terra e madeira misturados em água)',
    'Concentração, até 8 horas',
    'cl dr ma',
    'Você muda o clima ao redor (precipitação, temperatura, vento) em estágios, em um raio de 8 km.',
  ],
  [
    'Semiplano',
    'con',
    '1 ação',
    '18 metros',
    'S',
    '1 hora',
    'bx ma',
    'Cria um espaço extradimensional de 9 metros cúbicos, com porta que só você controla.',
  ],
  [
    'Dominar Monstro',
    'enc',
    '1 ação',
    '18 metros',
    'V, S',
    'Concentração, até 1 hora',
    'ba fe bx ma',
    'Qualquer criatura faz salvaguarda de Sabedoria ou fica sob seu controle telepático, com vantagem se ferida.',
    'Duração maior com círculo 9.',
  ],
  [
    'Terremoto',
    'evo',
    '1 ação',
    '150 metros',
    'V, S, M (uma pitada de terra, uma rocha e barro)',
    'Concentração, até 1 minuto',
    'cl dr fe',
    'Tremor num círculo de 30 metros de raio: criaturas caem, estruturas desabam e fissuras se abrem.',
  ],
  [
    'Enfraquecer Mente',
    'enc',
    '1 ação',
    '45 metros',
    'V, S, M (um punhado de argila, cristal, vidro ou esferas minerais)',
    'Instantânea',
    'ba dr bx ma',
    'Criatura faz salvaguarda de Inteligência ou sofre 4d6 de dano psíquico e fica com Inteligência e Carisma 1, incapaz de conjurar ou falar.',
  ],
  [
    'Lábia',
    'tra',
    '1 ação',
    'Pessoal',
    'V',
    '1 hora',
    'ba bx',
    'Você tem 15 como mínimo em testes de Carisma e sabe, ao mentir, driblar magias que detectam mentiras.',
  ],
  [
    'Aura Sagrada',
    'abj',
    '1 ação',
    'Pessoal',
    'V, S, M (um minúsculo relicário no valor de 1.000 po)',
    'Concentração, até 1 minuto',
    'cl',
    'Luz divina: aliados escolhidos têm vantagem em salvaguardas e atacantes têm desvantagem contra eles, e cegam corruptores e mortos-vivos.',
  ],
  [
    'Nuvem Incendiária',
    'con',
    '1 ação',
    '45 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'dr fe ma',
    'Nuvem de fumaça de 6 metros de raio que se move 3 metros por turno: 10d8 de dano de fogo (Destreza reduz à metade) e obscurece a visão.',
  ],
  [
    'Labirinto',
    'con',
    '1 ação',
    '18 metros',
    'V, S',
    'Concentração, até 10 minutos',
    'ma',
    'Prisão num semiplano de labirinto; a criatura sai ao passar num teste de Inteligência (CD 20) ou após 10 minutos.',
  ],
  [
    'Mente Impenetrável',
    'abj',
    '1 ação',
    'Toque',
    'V, S',
    '24 horas',
    'ba ma',
    'A criatura tocada fica imune a dano psíquico, leitura de pensamentos, adivinhação e encantamentos de controle.',
  ],
  [
    'Palavra de Poder: Atordoar',
    'enc',
    '1 ação',
    '18 metros',
    'V',
    'Instantânea',
    'ba bx fe ma',
    'Uma criatura com 150 PV ou menos fica atordoada, repetindo a salvaguarda de Constituição ao fim de cada turno.',
  ],
  [
    'Explosão Solar',
    'evo',
    '1 ação',
    '45 metros',
    'V, S, M (fogo e um pedaço de pedra-do-sol)',
    'Instantânea',
    'dr fe ma',
    'Esfera de luz de 18 metros de raio: 12d6 de dano radiante (Constituição reduz à metade) e cegueira. Mortos-vivos têm desvantagem.',
  ],
  [
    'Telepatia',
    'evo',
    '1 ação',
    'Ilimitada',
    'V, S, M (um par de anéis de prata ligados)',
    '24 horas',
    'ma',
    'Você cria um elo telepático com uma criatura que conhece, em qualquer distância, mesmo entre planos.',
  ],
  [
    'Tsunami',
    'con',
    '1 minuto',
    'Visão',
    'V, S',
    'Concentração, até 6 rodadas',
    'dr',
    'Muralha de água de até 90 metros de comprimento e 90 de altura avança 15 metros por turno: 6d10 de dano contundente e arrasta criaturas.',
  ],
];
