import type { SpellRow } from './types';

export const C9: readonly SpellRow[] = [
  [
    'Projeção Astral',
    'nec',
    '1 hora',
    '3 metros',
    'V, S, M (um jacinto de 1.000 po e uma barra de prata de 100 po para cada criatura)',
    'Especial',
    'cl bx ma',
    'Você e até oito criaturas projetam corpos astrais ao Plano Astral e viajam por planos; o corpo físico fica em animação suspensa.',
  ],
  [
    'Premonição',
    'adi',
    '1 minuto',
    'Toque',
    'V, S, M (uma pena de colibri)',
    '8 horas',
    'ba dr bx ma',
    'A criatura tocada não pode ser surpreendida; ganha vantagem em ataques, testes e salvaguardas, e atacantes têm desvantagem contra ela.',
  ],
  [
    'Portal',
    'con',
    '1 ação',
    '18 metros',
    'V, S, M (um diamante no valor de 5.000 po)',
    'Concentração, até 1 minuto',
    'cl fe bx ma',
    'Abre um portal para um plano específico; você pode chamar uma criatura pelo nome.',
  ],
  [
    'Aprisionamento',
    'abj',
    '1 minuto',
    '9 metros',
    'V, S, M (um pergaminho de imagem ou uma estatueta, pó de rubi no valor de 5.000 po)',
    'Até ser dissipada',
    'ma bx',
    'Prende uma criatura numa forma permanente (corrente, sepultamento, prisão, minúsculo, torpor).',
  ],
  [
    'Cura Completa',
    'evo',
    '1 ação',
    '18 metros',
    'V, S',
    'Instantânea',
    'cl',
    'Restaura 700 PV, cura cegueira, surdez e doenças a até seis criaturas.',
  ],
  [
    'Chuva de Meteoros',
    'evo',
    '1 ação',
    '1,5 quilômetro',
    'V, S',
    'Instantânea',
    'fe ma',
    'Quatro esferas de fogo atingem pontos que você escolhe: 20d6 de dano contundente e 20d6 de dano de fogo em esferas de 12 metros (Destreza reduz à metade).',
  ],
  [
    'Palavra de Poder: Cura',
    'evo',
    '1 ação',
    'Toque',
    'V, S',
    'Instantânea',
    'ba cl',
    'Restaura todos os PV de uma criatura e remove encanto, medo, paralisia, atordoamento e outros efeitos.',
  ],
  [
    'Palavra de Poder: Matar',
    'enc',
    '1 ação',
    '18 metros',
    'V, S',
    'Instantânea',
    'ba fe bx ma',
    'Uma criatura com 100 PV ou menos morre instantaneamente; com mais de 100 PV, sofre 12d12 de dano psíquico.',
  ],
  [
    'Muralha Prismática',
    'abj',
    '1 ação',
    '18 metros',
    'V, S',
    '10 minutos',
    'ba ma',
    'Barreira de luz com sete camadas; atravessá-la causa efeitos de dano ou condições, uma camada por vez.',
  ],
  [
    'Metamorfose',
    'tra',
    '1 ação',
    'Pessoal',
    'V, S, M (um diadema de jade no valor de 1.500 po)',
    'Concentração, até 1 hora',
    'dr ma',
    'Você assume a forma de qualquer criatura de ND até o seu nível, mantendo mente e PV da nova forma, e pode trocar de forma.',
  ],
  [
    'Tempestade de Vingança',
    'con',
    '1 ação',
    'Visão',
    'V, S',
    'Concentração, até 1 minuto',
    'dr',
    'Nuvem de tempestade de 100 metros de raio: a cada turno causa trovões, ácido, relâmpagos, granizo e vendaval, com dano crescente.',
  ],
  [
    'Parar o Tempo',
    'tra',
    '1 ação',
    'Pessoal',
    'V',
    'Instantânea',
    'fe ma',
    'O tempo para; você age por 1d4 + 1 turnos extras. Termina se você afetar outra criatura ou objeto levado por outro.',
  ],
  [
    'Polimorfia Verdadeira',
    'tra',
    '1 ação',
    '9 metros',
    'V, S, M (uma gota de mercúrio, goma-arábica e fumaça)',
    'Concentração, até 1 hora',
    'ba bx ma',
    'Transforma uma criatura em outra criatura ou objeto (ou o contrário). Após 1 hora de concentração, a mudança se torna permanente.',
  ],
  [
    'Ilusão Mortal',
    'ilu',
    '1 ação',
    '36 metros',
    'V, S',
    'Concentração, até 1 minuto',
    'bx ma',
    'Cria o maior medo de cada criatura numa esfera de 9 metros: 4d10 de dano psíquico por turno (Sabedoria resiste) até que a salvaguarda tenha sucesso.',
  ],
  [
    'Desejo',
    'con',
    '1 ação',
    'Pessoal',
    'V',
    'Instantânea',
    'fe ma',
    'A mais poderosa magia: replica qualquer magia de até 8º círculo ou realiza algo mais amplo, com riscos de estresse e de nunca mais poder conjurá-la.',
  ],
];
